import type { DatasetInfoRecord } from '@/components/DatasetInfo'

export const DATASETS = {
  foodSafety: {
    title: 'Food safety inspections',
    description: 'Food facility locations, hazard ratings, inspection dates, and violation history for Prince George.',
    source: 'Northern Health',
    coverage: 'Prince George food premises',
    license: 'Public health open data',
    formats: ['JSON'],
    downloadUrl: '/data/restaurants.json',
    fields: ['name', 'address', 'facility_type', 'hazard_rating', 'inspections', 'violations'],
  },
  airQuality: {
    title: 'Air monitoring stations',
    description: 'Regulatory, research, and community air monitoring station metadata with network, status, and measured parameters.',
    source: 'BC ENV, EPA, SPARTAN, ASCENT, PurpleAir',
    coverage: 'BC and North America, filtered to map view',
    license: 'Source-dependent open data',
    formats: ['CSV', 'JSON'],
    downloadUrl: '/data/monitors.csv',
    fields: ['name', 'network', 'status', 'parameters', 'latitude', 'longitude'],
  },
  census: {
    title: '2021 census variables',
    description: 'Census geography and variable extracts across census subdivision, tract, dissemination area, and block levels.',
    source: 'Statistics Canada 2021 Census',
    coverage: 'Prince George census geographies',
    license: 'Statistics Canada open licence',
    formats: ['JSON', 'GeoJSON'],
    downloadUrl: '/data/census/variables/catalog.json',
    fields: ['GeoUID', 'name', 'population', 'areaSqKm', 'variable_id', 'value'],
  },
  parks: {
    title: 'Parks, trails, and CityPG open layers',
    description: 'Parks, trails, amenities, mobility, ecology, service, and planning layers from Prince George open data.',
    source: 'City of Prince George Open Data',
    coverage: 'Prince George municipal boundary',
    license: 'City open data licence',
    formats: ['GeoJSON'],
    downloadUrl: '/data/parks.json',
    apiUrl: 'https://services2.arcgis.com/CnkB6jCzAsyli34z/arcgis/rest/services',
    fields: ['name', 'classification', 'userClass', 'geometry', 'sourceLayer'],
  },
  crime: {
    title: 'Property crime incidents',
    description: 'Property crime incidents with category, date, location, and community attributes.',
    source: 'City of Prince George / RCMP open data',
    coverage: 'Prince George communities',
    license: 'City open data licence',
    formats: ['GeoJSON'],
    apiUrl: 'https://services2.arcgis.com/CnkB6jCzAsyli34z/arcgis/rest/services/PGCrime/FeatureServer/0/query',
    fields: ['category', 'date', 'community', 'latitude', 'longitude'],
  },
  transit: {
    title: 'Transit routes and service geometry',
    description: 'Prince George transit route segments and related GTFS-derived service geometry.',
    source: 'BC Transit GTFS / City of Prince George',
    coverage: 'Prince George transit service area',
    license: 'Open transit data',
    formats: ['GeoJSON', 'GTFS-derived'],
    downloadUrl: '/data/transit/prince_george_gtfs_route_segments.geojson',
    fields: ['route_id', 'route_short_name', 'route_long_name', 'geometry'],
  },
  icbc: {
    title: 'ICBC reported crash locations',
    description: 'Reported crash-location counts from ICBC Tableau Public exports, filtered to Prince George and geocoded to CityPG intersection centroids where possible.',
    source: 'ICBC Tableau Public',
    coverage: 'Prince George crash-location summaries',
    license: 'ICBC Open Data Licence',
    formats: ['CSV', 'GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/icbc/manifest.json',
    fields: ['location', 'municipality', 'crashCount', 'longitude', 'latitude', 'geocodeMatchType'],
  },
  heatShade: {
    title: 'Heat and shade proxy layers',
    description: 'Tree, forest, facility, and remote-sensing metadata used as shade, heat, and cooling-access proxies.',
    source: 'City of Prince George Open Data and Microsoft Planetary Computer',
    coverage: 'Prince George and surrounding warm-season scene bbox',
    license: 'Source-dependent open data',
    formats: ['GeoJSON', 'JSON'],
    downloadUrl: '/data/heat-shade/manifest.json',
    fields: ['source', 'featureCount', 'bbox', 'sceneCount', 'years'],
  },
  canue: {
    title: 'CANUE BC annual extracts',
    description: 'Environmental exposure and neighbourhood indicators joined to BC and Prince George boundary layers.',
    source: 'CANUE',
    coverage: 'British Columbia extracts clipped/aggregated for mapped boundaries',
    license: 'CANUE research data terms',
    formats: ['CSV.GZ', 'JSON manifest'],
    downloadUrl: '/data/canue/bc/annual-gzip/manifest.json',
    fields: ['datasetId', 'category', 'year', 'postal_code', 'value'],
  },
  walkability: {
    title: 'Web-source walkability variants',
    description: 'Community-level walkability variants recalculated from CityPG web layers and ICBC public crash summaries.',
    source: 'City of Prince George Open Data and ICBC',
    coverage: 'Prince George community boundaries',
    license: 'Source-dependent open data',
    formats: ['GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/walkability/manifest.json',
    fields: ['communityName', 'balancedScore', 'infrastructureScore', 'accessScore', 'safetyAdjustedScore'],
  },
  bcAssessment: {
    title: 'BC Assessment properties',
    description: 'Parcel/property assessment extracts with value, year built, category, and location attributes.',
    source: 'BC Assessment / local extract',
    coverage: 'Prince George parcels',
    license: 'BC Assessment data terms',
    formats: ['CSV', 'GeoJSON'],
    downloadUrl: '/data/bc-assessment/parcels.geojson',
    fields: ['address', 'category', 'totalAssessed', 'yearBuilt', 'latitude', 'longitude'],
  },
  explorer: {
    title: 'Explorer catalogue',
    description: 'Unified searchable layer catalogue combining point, line, and polygon datasets across PGMaps.',
    source: 'PGMaps normalized local datasets',
    coverage: 'Prince George and supporting regional layers',
    license: 'Source-dependent open data',
    formats: ['CSV export', 'GeoJSON export'],
    fields: ['name', 'dataset', 'geometry', 'relevance', 'summary'],
  },
  scoreBuilder: {
    title: 'Index Lab input layers',
    description: 'Normalized indicator inputs used to build transparent civic, health, climate, and accessibility scores.',
    source: 'PGMaps normalized local datasets',
    coverage: 'Selected Prince George boundaries',
    license: 'Source-dependent open data',
    formats: ['URL state', 'CSV export'],
    fields: ['metric', 'weight', 'normalization', 'aggregation', 'regionScore'],
  },
} satisfies Record<string, DatasetInfoRecord>

export type DatasetKey = keyof typeof DATASETS
