import type { DatasetInfoRecord } from '@/components/DatasetInfo'

export const DATASETS = {
  foodSafety: {
    title: 'Food safety inspections',
    description: 'Food facility locations, hazard ratings, inspection dates, and violation history for Prince George.',
    source: 'Northern Health',
    coverage: 'Prince George food premises',
    license: 'Public health open data',
    formats: ['JSON'],
    downloadUrl: '/data/restaurants.json',
    fields: ['name', 'address', 'facility_type', 'hazard_rating', 'inspections', 'violations'],
  },
  airQuality: {
    title: 'Air monitoring stations',
    description: 'Regulatory, research, and community air monitoring station metadata with network, status, and measured parameters.',
    source: 'BC ENV, EPA, SPARTAN, ASCENT, PurpleAir',
    coverage: 'BC and North America, filtered to map view',
    license: 'Source-dependent open data',
    formats: ['CSV', 'JSON'],
    downloadUrl: '/data/monitors.csv',
    fields: ['name', 'network', 'status', 'parameters', 'latitude', 'longitude'],
  },
  census: {
    title: '2021 census variables',
    description: 'Census geography and variable extracts across census subdivision, tract, dissemination area, and block levels.',
    source: 'Statistics Canada 2021 Census',
    coverage: 'Prince George census geographies',
    license: 'Statistics Canada open licence',
    formats: ['JSON', 'GeoJSON'],
    downloadUrl: '/data/census/variables/catalog.json',
    fields: ['GeoUID', 'name', 'population', 'areaSqKm', 'variable_id', 'value'],
  },
  parks: {
    title: 'Parks, trails, and CityPG open layers',
    description: 'Parks, trails, amenities, mobility, ecology, service, and planning layers from Prince George open data.',
    source: 'City of Prince George Open Data',
    coverage: 'Prince George municipal boundary',
    license: 'City open data licence',
    formats: ['GeoJSON'],
    downloadUrl: '/data/parks.json',
    apiUrl: 'https://services2.arcgis.com/CnkB6jCzAsyli34z/arcgis/rest/services',
    fields: ['name', 'classification', 'userClass', 'geometry', 'sourceLayer'],
  },
  crime: {
    title: 'Property crime incidents',
    description: 'Property crime incidents with category, date, location, and community attributes.',
    source: 'City of Prince George / RCMP open data',
    coverage: 'Prince George communities',
    license: 'City open data licence',
    formats: ['GeoJSON'],
    apiUrl: 'https://services2.arcgis.com/CnkB6jCzAsyli34z/arcgis/rest/services/PGCrime/FeatureServer/0/query',
    fields: ['category', 'date', 'community', 'latitude', 'longitude'],
  },
  transit: {
    title: 'Transit routes and service geometry',
    description: 'Prince George transit route segments and related GTFS-derived service geometry.',
    source: 'BC Transit GTFS / City of Prince George',
    coverage: 'Prince George transit service area',
    license: 'Open transit data',
    formats: ['GeoJSON', 'GTFS-derived'],
    downloadUrl: '/data/transit/prince_george_gtfs_route_segments.geojson',
    fields: ['route_id', 'route_short_name', 'route_long_name', 'geometry'],
  },
  icbc: {
    title: 'ICBC reported crash locations',
    description: 'Reported crash-location counts from ICBC Tableau Public exports, filtered to Prince George and geocoded to CityPG intersection centroids where possible.',
    source: 'ICBC Tableau Public',
    coverage: 'Prince George crash-location summaries',
    license: 'ICBC Open Data Licence',
    formats: ['CSV', 'GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/icbc/manifest.json',
    fields: ['location', 'municipality', 'crashCount', 'longitude', 'latitude', 'geocodeMatchType'],
  },
  wars: {
    title: 'Wildlife accident records',
    description: 'Wildlife Accident Reporting System records filtered to Prince George nearest-town rows with source coordinates.',
    source: 'BC Ministry of Transportation and Transit Wildlife Accident Reporting System',
    coverage: 'Prince George nearest-town wildlife accident records',
    license: 'WARS Data Use Licence Agreement 2026',
    formats: ['XLSX source', 'CSV', 'GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/wars/manifest.json',
    apiUrl: 'https://www2.gov.bc.ca/gov/content/transportation/transportation-infrastructure/engineering-standards-guidelines/environmental-management/wildlife-management/wildlife-accident-reporting-system',
    fields: ['accidentDate', 'year', 'nearestTown', 'species', 'quantity', 'longitude', 'latitude'],
  },
  heatShade: {
    title: 'Heat and shade proxy layers',
    description: 'Tree, forest, facility, and remote-sensing metadata used as shade, heat, and cooling-access proxies.',
    source: 'City of Prince George Open Data and Microsoft Planetary Computer',
    coverage: 'Prince George and surrounding warm-season scene bbox',
    license: 'Source-dependent open data',
    formats: ['GeoJSON', 'JSON'],
    downloadUrl: '/data/heat-shade/manifest.json',
    fields: ['source', 'featureCount', 'bbox', 'sceneCount', 'years'],
  },
  canue: {
    title: 'CANUE BC annual extracts and PMTiles grid',
    description: 'Environmental exposure and neighbourhood indicators joined to boundaries, plus optimized 1 km BC PMTiles grid layers.',
    source: 'CANUE',
    coverage: 'British Columbia extracts clipped/aggregated for mapped boundaries',
    license: 'CANUE research data terms',
    formats: ['CSV.GZ', 'PMTiles', 'JSON catalog'],
    downloadUrl: '/data/canue/bc/annual-gzip/manifest.json',
    apiUrl: 'https://data.map.ahmad.sh/canue/pmtiles-v2/canue-bc-grid-v2-app-catalog.json',
    fields: ['datasetId', 'family', 'year', 'postal_code', 'property', 'value'],
  },
  walkability: {
    title: 'Web-source walkability variants',
    description: 'Community-level walkability variants recalculated from CityPG web layers and ICBC public crash summaries.',
    source: 'City of Prince George Open Data and ICBC',
    coverage: 'Prince George community boundaries',
    license: 'Source-dependent open data',
    formats: ['GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/walkability/manifest.json',
    fields: ['communityName', 'balancedScore', 'infrastructureScore', 'accessScore', 'safetyAdjustedScore'],
  },
  water: {
    title: 'Drinking water facilities, samples, and combined notices',
    description: 'Drinking water facilities with bacteriological sample rows, chemical result rows, and combined active water notices from HealthSpace and WaterToday.',
    source: 'BC drinking water public data extracts, Northern Health HealthSpace, and WaterToday',
    coverage: 'British Columbia drinking water facilities and active notices, mapped where coordinates are available',
    license: 'Source-dependent open data',
    formats: ['JSON', 'JSON manifest'],
    downloadUrl: '/data/water/combined_water_notices_summary.json',
    fields: ['facility_id', 'facility_name', 'latitude', 'longitude', 'sample_date', 'parameter', 'result', 'notice_type', 'primary_source', 'merge_bucket'],
  },
  flood: {
    title: 'BC River Forecast Centre flood context',
    description: 'Live streamflow return periods, CLEVER/COFFEE forecast station points, and RFC basin polygons for flood context.',
    source: 'BC River Forecast Centre',
    coverage: 'British Columbia hydrometric stations and RFC basins',
    license: 'Open Government Licence - British Columbia / source-dependent hydrometric terms',
    formats: ['ArcGIS FeatureServer', 'GeoJSON'],
    apiUrl: 'https://services6.arcgis.com/ubm4tcTYICKBpist/arcgis/rest/services',
    fields: ['Station_ID', 'Station_Name', 'Basin', 'Current_Reading_', 'Return_Period', 'Forecast_maximum_in_5_days', 'Return_Period_FOR'],
  },
  bcAssessment: {
    title: 'BC Assessment properties',
    description: 'Parcel/property assessment extracts with value, year built, category, and location attributes.',
    source: 'BC Assessment / local extract',
    coverage: 'Prince George parcels',
    license: 'BC Assessment data terms',
    formats: ['CSV', 'GeoJSON'],
    downloadUrl: '/data/bc-assessment/parcels.geojson',
    fields: ['address', 'category', 'totalAssessed', 'yearBuilt', 'latitude', 'longitude'],
  },
  drought: {
    title: 'B.C. drought levels time lapse',
    description: 'Historical drought basin polygons from the BC Drought Information Portal for 2015 through 2025.',
    source: 'BC Drought Information Portal / ArcGIS Hub',
    coverage: 'British Columbia drought basins',
    license: 'BC Government open data / ArcGIS Hub source terms',
    formats: ['GeoJSON', 'JSON manifest'],
    downloadUrl: '/data/drought/manifest.json',
    apiUrl: 'https://droughtportal.gov.bc.ca/search',
    fields: ['basinName', 'droughtLevel', 'startDate', 'endDate', 'geometry'],
  },
  cellCoverage: {
    title: 'Canada cell coverage tile sources',
    description: 'Provider-reported mobile coverage tile metadata for Rogers, TELUS, Bell, Videotron, and Freedom Mobile.',
    source: 'Carrier public coverage maps',
    coverage: 'Canada',
    license: 'Source-dependent carrier map terms',
    formats: ['JSON manifest', 'Raster tiles', 'Vector tiles'],
    downloadUrl: '/data/cell-coverage/manifest.json',
    fields: ['provider', 'technology', 'tileUrl', 'tilejsonUrl', 'bounds', 'minzoom', 'maxzoom'],
  },
  networkAvailability: {
    title: 'Canada network availability',
    description: 'Vector-first national mobile network availability sources, with CRTC coverage packages, NRCan hosted coverage, ISED cell-site points, and carrier API findings.',
    source: 'CRTC, NRCan, ISED, and carrier public coverage maps',
    coverage: 'Canada',
    license: 'Open Government Licence - Canada for CRTC/NRCan sources; source-dependent terms for ISED and carrier map metadata',
    formats: ['KML', 'MapInfo TAB', 'File Geodatabase', 'Esri REST', 'CSV ZIP', 'JSON manifest'],
    downloadUrl: '/data/network-availability/manifest.json',
    fields: ['dataset', 'geometry', 'format', 'contentLength', 'lastModified', 'carrierVectorStatus'],
  },
  explorer: {
    title: 'Explorer catalogue',
    description: 'Unified searchable layer catalogue combining point, line, and polygon datasets across PGMaps.',
    source: 'PGMaps normalized local datasets',
    coverage: 'Prince George and supporting regional layers',
    license: 'Source-dependent open data',
    formats: ['CSV export', 'GeoJSON export'],
    fields: ['name', 'dataset', 'geometry', 'relevance', 'summary'],
  },
  scoreBuilder: {
    title: 'Index Lab input layers',
    description: 'Normalized indicator inputs used to build transparent civic, health, climate, and accessibility scores.',
    source: 'PGMaps normalized local datasets',
    coverage: 'Selected Prince George boundaries',
    license: 'Source-dependent open data',
    formats: ['URL state', 'CSV export'],
    fields: ['metric', 'weight', 'normalization', 'aggregation', 'regionScore'],
  },
  healthyBuiltEnvironment: {
    title: 'Healthy Built Environment toolkit lenses',
    description:
      'PGMaps crosswalk from the BCCDC HBE Linkages Toolkit to local map layers for complete neighbourhoods, active transportation, natural environments, food systems, and housing.',
    source: 'BCCDC HBE Linkages Toolkit, PGMaps normalized local datasets',
    coverage: 'Prince George planning boundaries and census geographies',
    license: 'Toolkit content by PHSA/BCCDC; local layers are source-dependent open data',
    formats: ['Score presets', 'Indicator metadata'],
    fields: ['hbeFeature', 'planningPrinciple', 'metric', 'proxyConfidence', 'dataGap'],
  },
} satisfies Record<string, DatasetInfoRecord>

export type DatasetKey = keyof typeof DATASETS
