import { test } from 'vitest';import assert from 'node:assert/strict'
import {DriveController} from '../driveController'
import {roadPath,roadPlacement,nearestStation} from '../driveMath'
import {ll} from './scenario.mjs'
function map(){const state={center:{lng:-122,lat:54},zoom:12,bearing:35,pitch:20,roll:0,elevation:0,max:60,clamped:true,ground:500,terrain:true,calls:[],jumps:[]};const gesture={enabled:true,isEnabled(){return this.enabled},enable(){this.enabled=true},disable(){this.enabled=false}};return {state,dragPan:gesture,getCenter:()=>state.center,getZoom:()=>state.zoom,getBearing:()=>state.bearing,getPitch:()=>state.pitch,getRoll:()=>state.roll,getElevation:()=>state.elevation,getMaxPitch:()=>state.max,setMaxPitch:v=>state.max=v,getCenterClampedToGround:()=>state.clamped,setCenterClampedToGround:v=>state.clamped=v,getTerrain:()=>state.terrain,queryTerrainElevation:()=>state.ground,calculateCameraOptionsFromCameraLngLatAltRotation:(ll,alt,bearing,pitch,roll)=>{state.calls.push({ll,alt,bearing,pitch,roll});return{center:ll,zoom:17,bearing,pitch,roll,elevation:alt}},jumpTo:pose=>state.jumps.push(pose),stop(){}}}
const path=()=>roadPath([ll(0,0),ll(100,0),ll(100,100)])
const stations=()=>[{lng:ll(0,0)[0],lat:ll(0,0)[1],groundElevationMeters:500,distanceAlongMeters:0},{lng:ll(100,100)[0],lat:ll(100,100)[1],groundElevationMeters:520,distanceAlongMeters:200}]
const options=()=>({playing:false,speedMetersPerSecond:20,eyeHeightMeters:1.6,lookAt:null,spotBearing:0,yaw:0,tilt:0,onPosition(){}})
test('camera stays on original bend instead of cutting coarse station chord',()=>{const p=roadPlacement(path(),100);assert.ok(Math.abs(p.lng-ll(100,0)[0])<1e-7);assert.ok(Math.abs(p.lat-ll(100,0)[1])<1e-7)})
test('repeated road vertices do not divide by zero',()=>assert.equal(roadPath([ll(0,0),ll(0,0),ll(1,0)]).length,2))
test('explicit roll=0 reaches camera helper',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(0);c.tick(0,options());assert.equal(m.state.calls[0].roll,0)})
test('eye height is measured over rendered terrain',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(0);c.tick(0,options());assert.equal(m.state.calls[0].alt,501.6)})
test('paused unchanged camera does not jump every frame',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(0);for(let i=0;i<20;i++)c.tick(i*16,options());assert.equal(m.state.jumps.length,1)})
test('look-around updates paused camera without moving along road',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(30);c.tick(0,options());c.tick(16,{...options(),yaw:45});assert.equal(m.state.jumps.length,2);assert.deepEqual(m.state.calls[0].ll,m.state.calls[1].ll)})
test('unknown terrain holds playback and never invents altitude zero',()=>{const m=map(),c=new DriveController(m,path(),stations());m.state.ground=null;c.start(0);for(let i=0;i<60;i++)c.tick(i*100,{...options(),playing:true});assert.equal(m.state.calls.length,0);m.state.ground=500;c.tick(6100,{...options(),playing:true});assert.ok(m.state.calls[0].ll.distanceAlongMeters<3)})
test('non-finite camera cannot poison the renderer',()=>{const m=map(),c=new DriveController(m,path(),stations());m.calculateCameraOptionsFromCameraLngLatAltRotation=()=>({center:{lng:NaN,lat:54},zoom:17,roll:0});c.start(0);c.tick(0,options());assert.equal(m.state.jumps.length,0)})
test('endpoint callback fires once even if parent has not paused yet',()=>{const m=map(),c=new DriveController(m,path(),stations());let ends=0;c.start(199);for(let i=0;i<20;i++)c.tick(i*100,{...options(),playing:true,onReachEnd:()=>ends++});assert.equal(ends,1)})
test('exit restores viewpoint, gesture states and centre-clamping',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(0);assert.equal(m.dragPan.enabled,false);c.tick(0,options());c.stop();assert.equal(m.state.max,60);assert.equal(m.state.clamped,true);assert.equal(m.dragPan.enabled,true);assert.deepEqual(m.state.jumps.at(-1).center,[-122,54]);c.stop();assert.equal(m.state.jumps.length,2)})
test('nearest visibility station is distinct from moving eye position',()=>assert.equal(nearestStation(stations(),125),1))
test('hillside above eye can be centred above horizon',()=>{const m=map(),c=new DriveController(m,path(),stations());c.start(0);c.tick(0,{...options(),lookAt:{lng:-122,lat:54.01,elevationMeters:650}});assert.ok(m.state.calls[0].pitch>90)})

test('exit explicitly restores zero elevation when no elevation accessor exists',()=>{const m=map();delete m.getElevation;const c=new DriveController(m,path(),stations());c.start(0);c.tick(0,options());c.stop();assert.equal(m.state.jumps.at(-1).elevation,0)})
test('public centre elevation accessor is preserved on exit',()=>{const m=map();m.getCenterElevation=()=>123;const c=new DriveController(m,path(),stations());c.start(0);c.tick(0,options());c.stop();assert.equal(m.state.jumps.at(-1).elevation,123)})

test('preloaded terrain prevents a sea-level camera when MapLibre returns zero for unloaded ground',()=>{const m=map();m.state.ground=0;const c=new DriveController(m,path(),stations(),{elevationAt:()=>678});c.start(0);c.tick(0,options());assert.equal(m.state.calls[0].alt,679.6)})
test('pending or missing preview terrain holds playback even if the map returns zero',()=>{for(const source of [null,{elevationAt:()=>NaN}]){const m=map();m.state.ground=0;const c=new DriveController(m,path(),stations(),source);c.start(0);c.tick(0,{...options(),playing:true});assert.equal(m.state.calls.length,0)}})
test('road grade lifts the view while preserving eye clearance',()=>{const m=map();const c=new DriveController(m,path(),stations(),{elevationAt:(lng)=>500+(lng-ll(0,0)[0])*10000});c.start(30);c.tick(0,options());assert.ok(m.state.calls[0].pitch>90);assert.ok(m.state.calls[0].pitch<110)})

test('short camera target keeps foreground inside the clip range',()=>{const m=map();let used=false;m.calculateCameraOptionsFromTo=(from,alt,to,targetAlt)=>{used=true;assert.ok(Math.hypot(to.lng-from.lng,to.lat-from.lat)<.002);assert.ok(Math.abs(targetAlt-alt)<20);return{center:to,zoom:20,bearing:90,pitch:90,elevation:targetAlt}};const c=new DriveController(m,path(),stations(),{elevationAt:()=>678});c.start(0);c.tick(0,options());assert.ok(used);assert.equal(m.state.jumps[0].roll,0);assert.equal(m.state.calls.length,0)})
