import {
  BOUNDARY_SOURCE_OPTIONS as ALL_BOUNDARY_SOURCE_OPTIONS,
  createStudyAreaLevelOptions,
  getStudyAreaLevelLabel,
  type StudyAreaLevelOption,
  type StudyAreaSourceOption,
} from '@/lib/studyArea'
import type { BoundaryLevelConfig, CanueBoundaryLevel, CanueBoundarySource, MiscLayerId } from './types'

export const MISC_LAYERS: Array<{ id: MiscLayerId; label: string; color: string }> = [
  { id: 'trees', label: 'Tree canopy proxy', color: '#16a34a' },
  { id: 'forests', label: 'Forests', color: '#15803d' },
  { id: 'facilities', label: 'Cooling access proxy', color: '#0ea5e9' },
]

export const CANUE_SUPPORTED_SOURCES = new Set<string>([
  'bcHealth',
  'regionalDistrict',
  'census',
  'cityPG',
  'watershed',
  'nrAdmin',
])

export const CANUE_BOUNDARY_SOURCE_OPTIONS: Array<StudyAreaSourceOption<string>> = ALL_BOUNDARY_SOURCE_OPTIONS.map(
  (option) => {
    const supported = CANUE_SUPPORTED_SOURCES.has(option.value)
    return {
      value: option.value,
      label: option.label,
      description: option.description,
      group: option.group,
      disabled: !supported,
      disabledReason: supported
        ? undefined
        : 'Postal-code-to-boundary aggregation is not yet generated for this boundary type.',
    }
  },
)

export const CANUE_HEALTH_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['healthAuthority', 'hsda', 'lha', 'chsa'] as const),
]

export const CANUE_CENSUS_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['cd', 'csd', 'ct', 'da', 'db'] as const),
]

export const CANUE_CITY_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['elementarySchoolCatchment', 'secondarySchoolCatchment'] as const),
]

export const CANUE_REGIONAL_DISTRICT_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['regionalDistrict'] as const),
]

export const CANUE_WATERSHED_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['majorWatershed', 'watershedGroup', 'assessmentWatershed'] as const),
]

export const CANUE_NR_ADMIN_LEVEL_OPTIONS: Array<StudyAreaLevelOption<CanueBoundaryLevel>> = [
  ...createStudyAreaLevelOptions(['nrArea', 'nrRegion', 'nrDistrict'] as const),
]

export const CANUE_BOUNDARY_LEVEL_TO_SOURCE: Record<CanueBoundaryLevel, CanueBoundarySource> = {
  healthAuthority: 'bcHealth',
  hsda: 'bcHealth',
  lha: 'bcHealth',
  chsa: 'bcHealth',
  regionalDistrict: 'regionalDistrict',
  cd: 'census',
  csd: 'census',
  ct: 'census',
  da: 'census',
  db: 'census',
  elementarySchoolCatchment: 'cityPG',
  secondarySchoolCatchment: 'cityPG',
  majorWatershed: 'watershed',
  watershedGroup: 'watershed',
  assessmentWatershed: 'watershed',
  nrArea: 'nrAdmin',
  nrRegion: 'nrAdmin',
  nrDistrict: 'nrAdmin',
}

export const CANUE_BOUNDARY_CONFIG: Record<CanueBoundaryLevel, BoundaryLevelConfig> = {
  healthAuthority: {
    path: '/data/boundaries/BCMoH/simplified/health_authorities.json',
    idField: 'HLTH_AUTHORITY_CODE',
    nameField: 'HLTH_AUTHORITY_NAME',
    label: getStudyAreaLevelLabel('healthAuthority'),
  },
  hsda: {
    path: '/data/boundaries/BCMoH/simplified/health_service_delivery_areas.json',
    idField: 'HLTH_SERVICE_DLVR_AREA_CODE',
    nameField: 'HLTH_SERVICE_DLVR_AREA_NAME',
    label: getStudyAreaLevelLabel('hsda'),
  },
  lha: {
    path: '/data/boundaries/BCMoH/simplified/local_health_areas.json',
    idField: 'LOCAL_HLTH_AREA_CODE',
    nameField: 'LOCAL_HLTH_AREA_NAME',
    label: getStudyAreaLevelLabel('lha'),
  },
  chsa: {
    path: '/data/boundaries/BCMoH/simplified/community_health_service_areas.json',
    idField: 'CMNTY_HLTH_SERV_AREA_CODE',
    nameField: 'CMNTY_HLTH_SERV_AREA_NAME',
    label: getStudyAreaLevelLabel('chsa'),
  },
  regionalDistrict: {
    path: '/data/boundaries/BC/regional_districts.geojson',
    idField: 'LGL_ADMIN_AREA_ID',
    nameField: 'ADMIN_AREA_NAME',
    label: getStudyAreaLevelLabel('regionalDistrict'),
  },
  cd: {
    path: '/data/census/prince_george_cd.geo.json',
    idField: 'id',
    nameField: 'name',
    label: getStudyAreaLevelLabel('cd'),
  },
  csd: {
    path: '/data/census/prince_george_csd.geo.json',
    idField: 'id',
    nameField: 'name',
    label: getStudyAreaLevelLabel('csd'),
  },
  ct: {
    path: '/data/census/prince_george_ct.geo.json',
    idField: 'id',
    nameField: 'name',
    label: getStudyAreaLevelLabel('ct'),
  },
  da: {
    path: '/data/census/prince_george_da.geo.json',
    idField: 'id',
    nameField: 'name',
    label: getStudyAreaLevelLabel('da'),
  },
  db: {
    path: '/data/census/prince_george_db.geo.json',
    idField: 'id',
    nameField: 'name',
    label: getStudyAreaLevelLabel('db'),
  },
  elementarySchoolCatchment: {
    path: '/data/boundaries/CityPG/elementary_school_catchments.geojson',
    idField: 'OBJECTID',
    nameField: 'SchoolName',
    label: getStudyAreaLevelLabel('elementarySchoolCatchment'),
  },
  secondarySchoolCatchment: {
    path: '/data/boundaries/CityPG/secondary_school_catchments.geojson',
    idField: 'OBJECTID',
    nameField: 'SchoolNam',
    label: getStudyAreaLevelLabel('secondarySchoolCatchment'),
  },
  majorWatershed: {
    path: '/data/boundaries/BCFWA/major_watersheds_province_simplified.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('majorWatershed'),
  },
  watershedGroup: {
    path: '/data/boundaries/BCFWA/watershed_groups_province_simplified.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('watershedGroup'),
  },
  assessmentWatershed: {
    path: '/data/boundaries/BCFWA/assessment_watersheds.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('assessmentWatershed'),
  },
  nrArea: {
    path: '/data/boundaries/BCNR/nr_areas.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('nrArea'),
  },
  nrRegion: {
    path: '/data/boundaries/BCNR/nr_regions.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('nrRegion'),
  },
  nrDistrict: {
    path: '/data/boundaries/BCNR/nr_districts.geojson',
    idField: 'boundaryCode',
    nameField: 'boundaryName',
    label: getStudyAreaLevelLabel('nrDistrict'),
  },
}

export const CANUE_DEFAULT_VARIABLE_BY_DATASET: Partial<Record<string, string>> = {
  ale_a: 'ale16_06',
  nhbic_ava: 'nhbic21_09',
  nhpmd_ann: 'nhpmd19_03',
}

export const CANUE_INVALID_NUMERIC_VALUES = new Set([-9999, -1111])

export const CANUE_EXACT_VARIABLE_LABELS: Record<string, string> = {
  pm25dal21_01: 'Annual mean PM2.5',
  lgtnlt13_01: 'Night-time light intensity',
  aqsmk22_01: 'Smoke PM2.5 mean',
  aqsmk22_02: 'Smoke PM2.5 median',
  aqsmk22_03: 'Smoke PM2.5 minimum',
  aqsmk22_04: 'Smoke PM2.5 maximum',
  aqsmk22_05: 'Smoke PM2.5 standard deviation',
}

export const CANUE_SUFFIX_LABELS_BY_DATASET: Record<string, Record<string, string>> = {
  no2lur_a: {
    '01': 'Original annual NO2 concentration, circa 2006',
    '02': 'Annual average NO2 concentration for selected year',
    '03': 'Census division identifier',
    '05': 'Distance to census division boundary',
  },
  aqaix_ava: {
    '01': 'Index 1 - combustion mixture',
    '02': 'Index 2 - ozone/ammonia mixture',
    '03': 'Index 3 - ammonia/agriculture mixture',
    '04': 'Carbon monoxide (CO)',
    '05': 'Formaldehyde column (HCHO)',
    '06': 'Ammonia (NH3)',
    '07': 'Nitrogen dioxide (NO2)',
    '08': 'Ozone (O3)',
    '09': 'Fine particulate matter (PM2.5)',
    '10': 'Sulfur dioxide (SO2)',
  },
  pm25dale_a: {
    '01': 'Annual mean PM2.5',
  },
  aqsmk_avb: {
    '01': 'Smoke PM2.5 mean',
    '02': 'Smoke PM2.5 median',
    '03': 'Smoke PM2.5 minimum',
    '04': 'Smoke PM2.5 maximum',
    '05': 'Smoke PM2.5 standard deviation',
  },
  aqsmk_avc: {
    '01': 'Smoke PM2.5 mean',
    '02': 'Smoke PM2.5 median',
    '03': 'Smoke PM2.5 minimum',
    '04': 'Smoke PM2.5 maximum',
    '05': 'Smoke PM2.5 standard deviation',
  },
  aqsmk_ava: {
    '01': 'Annual smoke PM2.5',
    '02': 'Autumn smoke PM2.5',
    '03': 'Spring smoke PM2.5',
    '04': 'Summer smoke PM2.5',
    '05': 'Winter smoke PM2.5',
  },
  o3chg_a: {
    '01': 'Annual average O3',
    '02': 'Warm-season average O3',
    '03': 'Annual highest rolling 8-hour O3 average',
    '04': 'Warm-season highest rolling 8-hour O3 average',
  },
  dtw_a: {
    '02': 'Distance to reservoir, pond, or lake',
    '03': 'Distance to watercourse, tidal river, or side channel',
    '04': 'Distance to canal',
    '05': 'Distance to other water bodies',
  },
  wbnrc_a: {
    '01': 'Annual minimum of monthly lowest daily maximum temperature',
    '02': 'Annual maximum of monthly highest daily minimum temperature',
    '03': 'Annual total precipitation',
    '04': 'Annual total rainfall',
    '05': 'Annual total snowfall',
    '06': 'Snow-to-rain ratio',
    '07': 'Annual total snow melt',
    '08': 'Maximum monthly snow-pack thickness',
    '09': 'Days with snowfall',
    '10': 'Days with snow on the ground',
    '11': 'Days with precipitation',
    '12': 'Potential evapotranspiration / water demand',
    '13': 'Actual evapotranspiration',
    '14': 'Water surplus',
    '15': 'Water deficit',
    '16': 'Days with water surplus',
    '17': 'Days with water deficit',
    '18': 'Sum of monthly average soil moisture',
    '19': 'Average monthly minimum soil moisture',
    '20': 'Minimum monthly soil moisture',
    '21': 'Wetness/dryness index',
  },
  wthnrc_a: {
    '01': 'Climate metric 01 - temperature',
    '02': 'Climate metric 02 - temperature',
    '03': 'Climate metric 03 - temperature',
    '04': 'Climate metric 04 - precipitation',
    '05': 'Climate metric 05 - precipitation',
    '06': 'Climate metric 06 - precipitation',
    '07': 'Climate metric 07 - temperature extreme',
    '08': 'Climate metric 08 - temperature extreme',
    '09': 'Climate metric 09 - heat days',
    '10': 'Climate metric 10 - cold days',
    '11': 'Climate metric 11 - degree days',
    '12': 'Climate metric 12 - degree days',
    '13': 'Climate metric 13 - degree days',
    '14': 'Climate metric 14 - seasonal temperature',
    '15': 'Climate metric 15 - seasonal temperature',
    '16': 'Climate metric 16 - wet days',
    '17': 'Climate metric 17 - heavy precipitation',
    '18': 'Climate metric 18 - snowfall days',
    '19': 'Climate metric 19 - rainfall days',
    '20': 'Climate metric 20 - dry spell',
    '21': 'Climate metric 21 - wet spell',
    '22': 'Climate metric 22 - spring temperature',
    '23': 'Climate metric 23 - summer temperature',
    '24': 'Climate metric 24 - autumn temperature',
    '25': 'Climate metric 25 - winter temperature',
    '26': 'Climate metric 26 - spring precipitation',
    '27': 'Climate metric 27 - summer precipitation',
    '28': 'Climate metric 28 - autumn precipitation',
    '29': 'Climate metric 29 - winter precipitation',
    '30': 'Climate metric 30 - heat index',
    '31': 'Climate metric 31 - cold index',
    '32': 'Climate metric 32 - temperature variability',
    '33': 'Climate metric 33 - precipitation variability',
    '34': 'Climate metric 34 - snow/rain',
    '35': 'Climate metric 35 - climate summary',
  },
  wtlst_ava: {
    '01': 'Land surface temperature at postal code',
    '02': '3-year annual max of 100m means',
    '03': '3-year annual max of 250m means',
    '04': '3-year annual max of 500m means',
    '05': '3-year annual max of 750m means',
    '06': '3-year annual max of 1km means',
  },
  wtfsi_ava: {
    '01': 'Flood susceptibility index',
    '02': 'Flood susceptibility lower estimate',
    '03': 'Flood susceptibility median estimate',
    '04': 'Flood susceptibility upper estimate',
    '05': 'Flood susceptibility class',
  },
  grlan_amn: {
    '01': 'Annual mean NDVI at postal code',
    '02': 'Annual mean NDVI within 100m',
    '03': 'Annual mean NDVI within 250m',
    '04': 'Annual mean NDVI within 500m',
    '05': 'Annual mean NDVI within 1km',
    '06': 'Annual maximum mean NDVI within 100m',
    '07': 'Annual maximum mean NDVI within 250m',
    '08': 'Annual maximum mean NDVI within 500m',
    '09': 'Annual maximum mean NDVI within 1km',
  },
  grlan_gmn: {
    '10': 'Growing-season mean NDVI at postal code',
    '11': 'Growing-season mean NDVI within 100m',
    '12': 'Growing-season mean NDVI within 250m',
    '13': 'Growing-season mean NDVI within 500m',
    '14': 'Growing-season mean NDVI within 1km',
    '15': 'Growing-season maximum mean NDVI within 100m',
    '16': 'Growing-season maximum mean NDVI within 250m',
    '17': 'Growing-season maximum mean NDVI within 500m',
    '18': 'Growing-season maximum mean NDVI within 1km',
  },
  grlan_gp: {
    '19': 'Greenest-pixel NDVI at postal code',
    '20': 'Mean greenest-pixel NDVI within 100m',
    '21': 'Mean greenest-pixel NDVI within 250m',
    '22': 'Mean greenest-pixel NDVI within 500m',
    '23': 'Mean greenest-pixel NDVI within 1km',
    '24': 'Maximum greenest-pixel NDVI within 100m',
    '25': 'Maximum greenest-pixel NDVI within 250m',
    '26': 'Maximum greenest-pixel NDVI within 500m',
    '27': 'Maximum greenest-pixel NDVI within 1km',
  },
  gravh_amn: {
    '01': 'AVHRR NDVI at postal code',
    '02': 'AVHRR NDVI within 100m',
    '03': 'AVHRR NDVI within 250m',
  },
  grmod_amnb: {
    '01': 'Modeled annual mean greenness at postal code',
    '02': 'Modeled annual mean greenness within 100m',
    '03': 'Modeled annual mean greenness within 250m',
    '04': 'Modeled annual mean greenness within 500m',
    '05': 'Modeled annual mean greenness within 1km',
  },
  grmod_amxb: {
    '06': 'Modeled annual maximum greenness at postal code',
    '07': 'Modeled annual maximum greenness within 100m',
    '08': 'Modeled annual maximum greenness within 250m',
    '09': 'Modeled annual maximum greenness within 500m',
    '10': 'Modeled annual maximum greenness within 1km',
  },
  grmod_gmnb: {
    '11': 'Modeled growing-season mean greenness at postal code',
    '12': 'Modeled growing-season mean greenness within 100m',
    '13': 'Modeled growing-season mean greenness within 250m',
    '14': 'Modeled growing-season mean greenness within 500m',
    '15': 'Modeled growing-season mean greenness within 1km',
  },
  grmod_gmxb: {
    '16': 'Modeled growing-season maximum greenness at postal code',
    '17': 'Modeled growing-season maximum greenness within 100m',
    '18': 'Modeled growing-season maximum greenness within 250m',
    '19': 'Modeled growing-season maximum greenness within 500m',
    '20': 'Modeled growing-season maximum greenness within 1km',
  },
  grtcc_ava: {
    '01': 'Tree canopy cover',
    '02': 'Tree canopy cover within 100m',
    '03': 'Tree canopy cover within 250m',
    '04': 'Tree canopy cover within 500m',
    '05': 'Tree canopy cover within 1km',
  },
  lcz_a: {
    '02': 'Dense urban percentage within 1km',
    '03': 'Open urban percentage within 1km',
    '04': 'Residential percentage within 1km',
    '05': 'Industrial/commercial/paved percentage within 1km',
    '06': 'Natural percentage within 1km',
    '07': 'Water percentage within 1km',
    '08': 'Unknown land-cover percentage within 1km',
  },
  cmg_a: {
    '04': 'Dissemination/enumeration area identifier',
    '05': 'Distance to nearest dissemination area',
    '06': 'Instability quintile',
    '07': 'Deprivation quintile',
    '08': 'Dependency quintile',
    '09': 'Ethnic concentration quintile',
    '10': 'Instability factor score',
    '11': 'Deprivation factor score',
    '12': 'Dependency factor score',
    '13': 'Ethnic concentration factor score',
  },
  indmsd_a: {
    '01': 'Dissemination area identifier',
    '02': 'Dissemination area population',
    '03': 'Census subdivision',
    '04': 'Province',
    '08': 'Material deprivation factor score',
    '09': 'Social deprivation factor score',
    '10': 'Material deprivation quintile within Canada',
    '11': 'Social deprivation quintile within Canada',
    '12': 'Material deprivation percentile within Canada',
    '13': 'Social deprivation percentile within Canada',
    '14': 'Material deprivation quintile within region',
    '15': 'Social deprivation quintile within region',
    '16': 'Material deprivation quintile within zone',
    '17': 'Social deprivation quintile within zone',
  },
  ale_a: {
    '01': 'Dissemination area ID',
    '02': 'Intersection density',
    '03': 'Dwelling density',
    '04': 'Intersection density z-score',
    '05': 'Dwelling density z-score',
    '06': 'ALE index',
    '07': 'ALE class',
    '08': 'Points of interest',
    '09': 'Points of interest z-score',
    '10': 'Transit stops',
    '11': 'Transit z-score',
    '12': 'ALE transit index',
    '13': 'ALE transit class',
  },
  dtr_a: {
    '01': 'Distance to expressways',
    '02': 'Distance to primary highways',
    '03': 'Distance to secondary highways',
    '04': 'Distance to major roads',
    '05': 'Distance to local roads',
  },
  nhacs_ava: {
    '01': 'Spatial accessibility measure 01',
  },
  nhbic_ava: {
    '01': 'Dissemination area ID',
    '02': 'ALE index',
    '03': 'ALE class',
    '04': 'Bike-to-work rate',
    '05': 'Sustainable transportation to work rate',
    '06': 'High-comfort bike infrastructure',
    '07': 'Medium-comfort bike infrastructure',
    '08': 'Low-comfort bike infrastructure',
    '09': 'Can-BICS index',
    '10': 'Can-BICS category',
  },
  nhspw_ava: {
    '01': 'Sprawl score',
    '02': 'Sprawl lower credible interval',
    '03': 'Sprawl median',
    '04': 'Sprawl upper credible interval',
  },
  nhpmd_ann: {
    '01': 'Dissemination block ID',
    '02': 'Employment in block',
    '03': 'Proximity to employment',
    '04': 'Pharmacy in block',
    '05': 'Proximity to pharmacy',
    '06': 'Childcare in block',
    '07': 'Proximity to childcare',
    '08': 'Health facility in block',
    '09': 'Proximity to health facility',
    '10': 'Grocery store in block',
    '11': 'Proximity to grocery store',
    '12': 'Primary education in block',
    '13': 'Proximity to primary education',
    '14': 'Secondary education in block',
    '15': 'Proximity to secondary education',
    '16': 'Library in block',
    '17': 'Proximity to library',
    '18': 'Park in block',
    '19': 'Proximity to park',
    '20': 'Transit stop in block',
    '21': 'Proximity to transit trips',
  },
}

export { BC_CENTER } from '@/components/ui/map-styles'
export const CANUE_MONTHS = [
  { value: 1, key: 'jan', label: 'January' },
  { value: 2, key: 'feb', label: 'February' },
  { value: 3, key: 'mar', label: 'March' },
  { value: 4, key: 'apr', label: 'April' },
  { value: 5, key: 'may', label: 'May' },
  { value: 6, key: 'jun', label: 'June' },
  { value: 7, key: 'jul', label: 'July' },
  { value: 8, key: 'aug', label: 'August' },
  { value: 9, key: 'sep', label: 'September' },
  { value: 10, key: 'oct', label: 'October' },
  { value: 11, key: 'nov', label: 'November' },
  { value: 12, key: 'dec', label: 'December' },
] as const

export const CANUE_MONTH_BY_VALUE: Map<number, (typeof CANUE_MONTHS)[number]> = new Map(
  CANUE_MONTHS.map((month) => [month.value, month]),
)
export const CANUE_MONTH_BY_KEY: Map<string, (typeof CANUE_MONTHS)[number]> = new Map(
  CANUE_MONTHS.map((month) => [month.key, month]),
)
export const CANUE_MONTH_PATTERN = /_(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)_\d{2}$/i
export const CANUE_ANNUAL_YEAR_PATTERN = /^(.*?)(\d{2})(_\d+)$/

export const CANUE_DATASET_SUFFIX_LABELS: Record<string, Record<string, string>> = {
  wtutv: {
    '01': 'Mean daily Vitamin D dose at sea level',
    '02': 'Mean daily Vitamin D dose at altitude',
    '03': 'Mean noon Vitamin D index at sea level',
    '04': 'Mean noon Vitamin D index at altitude',
    '05': '95th percentile noon Vitamin D index at sea level',
    '06': '95th percentile noon Vitamin D index at altitude',
  },
  wtwbm: {
    '01': 'Average daily maximum temperature',
    '02': 'Highest daily maximum temperature',
    '03': 'Lowest daily maximum temperature',
    '04': 'Average daily minimum temperature',
    '05': 'Highest daily minimum temperature',
    '06': 'Lowest daily minimum temperature',
    '07': 'Monthly mean temperature',
    '08': 'Monthly total precipitation',
    '09': 'Monthly total rainfall',
    '10': 'Monthly total snowfall',
    '11': 'Days with precipitation',
    '12': 'Days with snowfall',
    '13': 'Days with snow on the ground',
    '14': 'Average snow-pack thickness',
    '15': 'Monthly total snow melt',
    '16': 'Potential evapotranspiration / water demand',
    '17': 'Actual evapotranspiration',
    '18': 'Water surplus',
    '19': 'Days with water surplus',
    '20': 'Water deficit',
    '21': 'Days with water deficit',
    '22': 'Average soil moisture',
    '23': 'Minimum soil moisture',
    '24': 'Wetness/dryness index',
  },
}

export const CANUE_V2_DATASET_LABELS: Record<string, string> = {
  aqaix_ava: 'Annual air quality health index',
  aqfpm_01: 'Monthly PM2.5',
  aqfpm_avf: 'Annual PM2.5 v6',
  aqno2_ra: 'Monthly NO2 land-use regression',
  aqozn_8h: 'Monthly O3 8-hour',
  aqozn_mn: 'Monthly O3 mean',
  aqsmk_01: 'Monthly smoke PM2.5',
  aqsmk_ava: 'Annual smoke PM2.5',
  aqsmk_avb: 'Annual smoke PM2.5 v2',
  aqsmk_avc: 'Annual smoke PM2.5 v3',
  no2lur_a: 'Annual NO2 land-use regression',
  o3chg_a: 'Annual O3 concentration',
  pm25dal_a: 'Annual PM2.5 DAL',
  pm25dalb_a: 'Annual PM2.5 DAL v2',
  pm25dalc_a: 'Annual PM2.5 DAL v3',
  pm25dald_a: 'Annual PM2.5 DAL v4',
  pm25dale_a: 'Annual PM2.5 DAL v5',
  so2omi_a: 'Annual SO2 OMI',
  dtw_a: 'Distance to water',
  wthnrc_a: 'Climate metrics',
  wtutv_01: 'Ultraviolet',
  wtutv_02: 'Ultraviolet',
  wtutv_03: 'Ultraviolet',
  wtutv_04: 'Ultraviolet',
  wtutv_05: 'Ultraviolet',
  wtutv_06: 'Ultraviolet',
  wbnrc_a: 'Annual water balance metrics',
  dtr_a: 'Distance to roads',
  wtlst_ava: 'Land surface temperature',
  wtfsi_ava: 'Flood susceptibility index',
  wtwbm_01: 'Monthly water balance metrics',
  wtwbm_02: 'Monthly water balance metrics',
  wtwbm_03: 'Monthly water balance metrics',
  wtwbm_04: 'Monthly water balance metrics',
  wtwbm_05: 'Monthly water balance metrics',
  wtwbm_06: 'Monthly water balance metrics',
  wtwbm_07: 'Monthly water balance metrics',
  wtwbm_08: 'Monthly water balance metrics',
  wtwbm_09: 'Monthly water balance metrics',
  wtwbm_10: 'Monthly water balance metrics',
  wtwbm_11: 'Monthly water balance metrics',
  wtwbm_12: 'Monthly water balance metrics',
  wtwbm_14: 'Monthly water balance metrics',
  wtwbm_15: 'Monthly water balance metrics',
  wtwbm_16: 'Monthly water balance metrics',
  wtwbm_17: 'Monthly water balance metrics',
  wtwbm_18: 'Monthly water balance metrics',
  wtwbm_19: 'Monthly water balance metrics',
  wtwbm_20: 'Monthly water balance metrics',
  wtwbm_21: 'Monthly water balance metrics',
  wtwbm_22: 'Monthly water balance metrics',
  wtwbm_23: 'Monthly water balance metrics',
  wtwbm_24: 'Monthly water balance metrics',
  grlan_amn: 'Land greenness - annual mean NDVI',
  grlan_gmn: 'Land greenness - growing-season mean NDVI',
  grlan_gp: 'Land greenness - greenest-pixel NDVI',
  gravh_amn: 'AVHRR NDVI',
  grmod_amnb: 'Modeled greenness - annual mean',
  grmod_amxb: 'Modeled greenness - annual maximum',
  grmod_gmnb: 'Modeled greenness - growing-season mean',
  grmod_gmxb: 'Modeled greenness - growing-season maximum',
  grtcc_ava: 'Tree canopy cover',
  lcz_a: 'Local climate zone',
  cmg_a: 'Canadian marginalization index',
  indmsd_a: 'Material and social deprivation',
  ale_a: 'Active living environment',
  nae_a: 'Employment accessibility',
  nhnse_ava: 'Neighborhood socioeconomic status',
  nhspw_ava: 'Urban sprawl',
  nhdwl_ava: 'Dwelling density',
  nhgrd_ava: 'Green roads',
  nhfed_ava: 'Food environment density',
  nhbld_ava: 'Building density',
  nhfac_ava: 'Facility richness and density',
  nhpmd_ann: 'Proximity to amenities',
  nhscn_ava: 'Street connectivity',
  nhtsp_ava: 'Transit stop access',
  nhacs_ava: 'Spatial accessibility measures',
  nhbic_ava: 'Bikeability',
  nhcmd_ann: 'Complete communities',
  nhhpp_ava: 'Healthy places priority',
  nhnse_avb: 'Neighborhood socioeconomic status v2',
  nhply_ann: 'Playability',
  lgtnlt_a: 'Night-time light brightness',
}

export const CANUE_V2_PREFERRED_MEASURE_KEYS = ['aqfpm_01__pm25', 'aqsmk_01__aqsmk_01', 'pm25dale_a__pm25dal_01']

export const CANUE_TIMELINE_WINDOW_OPTIONS = [
  { value: 1, label: '1' },
  { value: 3, label: '3' },
  { value: 5, label: '5' },
  { value: -1, label: 'Cumul.' },
]
