export {
  BOUNDARY_SOURCE_OPTIONS,
  HEALTH_BOUNDARY_LEVEL_OPTIONS,
  CENSUS_BOUNDARY_LEVEL_OPTIONS,
  REGIONAL_DISTRICT_BOUNDARY_LEVEL_OPTIONS,
  CITY_BOUNDARY_LEVEL_OPTIONS,
  WATERSHED_BOUNDARY_LEVEL_OPTIONS,
  NR_ADMIN_BOUNDARY_LEVEL_OPTIONS,
  BOUNDARY_FILE_BY_LEVEL,
  BOUNDARY_INDEX_KEY_BY_LEVEL,
  BOUNDARY_CODE_PROPERTY_BY_LEVEL,
  BOUNDARY_NAME_PROPERTY_BY_LEVEL,
} from '@/lib/studyArea'
import { HEALTH_BOUNDARY_LEVEL_OPTIONS as _SCORE_BUILDER_HEALTH_BOUNDARY_LEVEL_OPTIONS } from '@/lib/studyArea'

// Backward-compatible alias used by existing imports.
export const BOUNDARY_LEVEL_OPTIONS = _SCORE_BUILDER_HEALTH_BOUNDARY_LEVEL_OPTIONS
