import type { ScoreExample, ScoreMethodSettings } from '../types'
import { MODULE_PERCENTILE_METHOD, PERCENTILE_METHOD, WINSORIZED_METHOD, Z_SCORE_METHOD } from './methodSettings'
import { ZERO_WEIGHTS } from './weights'

export const SCORE_EXAMPLES: ScoreExample[] = [
  // ── Community polygons ───────────────────────────────────────────────

  // 31 CityPG community areas — the default cold-start recipe
  {
    key: 'greenestNeighbourhoods',
    label: 'Greenest Neighbourhoods',
    question: 'Which parts of PG have the best park and trail access?',
    description:
      'Scores each of the 31 CityPG communities by park coverage, trail density, and amenity access. High-scoring areas have more green space per resident.',
    boundarySource: 'cityCommunity',
    boundaryLevel: 'communityPolygon',
    dataSources: ['parks', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      parkDensity: 22,
      parkAreaRatio: 28,
      trailDensity: 20,
      amenityDensity: 15,
      populationDensity: 15,
    },
  },

  // ── Census boundaries ────────────────────────────────────────────────
  {
    key: 'airQualityGapsCt',
    label: 'Air Monitoring Gaps (Tract)',
    question: 'Which PG tracts are underserved by air quality sensors?',
    description:
      'Highlights census tracts where sensor density is low relative to population. Low-scoring tracts are monitoring blind spots.',
    boundarySource: 'census',
    boundaryLevel: 'ct',
    dataSources: ['airQuality', 'census'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      overallDensity: 30,
      lowCostDensity: 15,
      referenceDensity: 20,
      networkVariety: 8,
      activeShare: 7,
      populationDensity: -20,
    },
  },
  {
    key: 'foodSafetyCt',
    label: 'Food Safety Landscape (Tract)',
    question: 'How does restaurant density and food safety risk vary across PG tracts?',
    description:
      'Scores each tract by restaurant access and inspection risk. Negative weight on food risk means safer areas score higher.',
    boundarySource: 'census',
    boundaryLevel: 'ct',
    dataSources: ['parks', 'restaurants', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      restaurantDensity: 35,
      foodRiskScore: -30,
      populationDensity: 20,
      amenityDensity: 15,
    },
  },
  {
    key: 'communityLivabilityCt',
    label: 'Community Livability (Tract)',
    question: 'Which PG tracts score highest across parks, food, air quality, and population?',
    description:
      'A holistic index blending all available data at the tract level. Best-scoring areas have parks, food options, air monitoring, and population.',
    boundarySource: 'census',
    boundaryLevel: 'ct',
    dataSources: ['airQuality', 'parks', 'restaurants', 'census'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      parkAreaRatio: 15,
      parkDensity: 10,
      trailDensity: 10,
      amenityDensity: 5,
      restaurantDensity: 10,
      foodRiskScore: -10,
      overallDensity: 12,
      activeShare: 5,
      networkVariety: 3,
      populationDensity: 10,
      lowCostDensity: 5,
      referenceDensity: 5,
    },
  },

  // Dissemination Area (DA) – 135 areas, fine-grained analysis
  {
    key: 'lowCostSensorDeploymentDa',
    label: 'Community Sensor Gaps (DA)',
    question: 'Where should community air sensors be prioritized at the block level?',
    description:
      'Uses 135 dissemination areas to find fine-grained gaps. Areas with high population but few PA/EGG sensors score lowest.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['airQuality', 'census'],
    networkFilter: ['PA', 'EGG'],
    weights: {
      ...ZERO_WEIGHTS,
      lowCostDensity: 35,
      overallDensity: 15,
      activeShare: 10,
      populationDensity: -25,
      parameterVariety: 8,
      networkVariety: 7,
    },
  },
  {
    key: 'parkAccessDa',
    label: 'Park Access (DA)',
    question: 'Which small neighbourhoods have the least green space access?',
    description:
      'Fine-grained view using 135 dissemination areas. Low-scoring areas lack nearby parks, trails, and amenities relative to their population.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['parks', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      parkDensity: 20,
      parkAreaRatio: 30,
      trailDensity: 18,
      amenityDensity: 12,
      populationDensity: -20,
    },
  },
  {
    key: 'foodAccessDa',
    label: 'Food Access (DA)',
    question: 'Which dissemination areas are food deserts or have high inspection risk?',
    description:
      'Fine-grained restaurant coverage across 135 areas. Highlights both under-served areas and areas with high food safety risk.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['parks', 'restaurants', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      restaurantDensity: 40,
      foodRiskScore: -25,
      populationDensity: 20,
      amenityDensity: 15,
    },
  },
  {
    key: 'livabilityDa',
    label: 'Livability Index (DA)',
    question: 'Holistic livability scored at the most granular level in PG?',
    description: 'Blends all data sources across 135 dissemination areas for the most detailed livability picture.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['airQuality', 'parks', 'restaurants', 'census'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      parkAreaRatio: 15,
      parkDensity: 8,
      trailDensity: 8,
      amenityDensity: 5,
      restaurantDensity: 8,
      foodRiskScore: -8,
      overallDensity: 12,
      activeShare: 6,
      networkVariety: 4,
      populationDensity: 12,
      lowCostDensity: 6,
      referenceDensity: 7,
    },
  },
  {
    key: 'pgClimateHealthVulnerabilityDa',
    label: 'PG Climate + Health Vulnerability Proxy (DA)',
    question: 'Which small areas have higher cumulative climate and community-health vulnerability?',
    description:
      'Research-backed starter index that combines exposure proxies, population sensitivity, property vulnerability, and adaptive capacity. High scores mark areas needing closer review.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['airQuality', 'parks', 'heatShade', 'restaurants', 'census', 'bcAssessment', 'crime'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      populationDensity: 18,
      overallDensity: -14,
      lowCostDensity: -8,
      referenceDensity: -10,
      parkAreaRatio: -16,
      treeDensity: -8,
      forestAreaRatio: -8,
      coolingFacilityDensity: -4,
      trailDensity: -8,
      amenityDensity: -6,
      avgAssessedValue: -10,
      vacantParcelShare: 7,
      buildingAge: 8,
      crimePerCapita: 8,
      foodRiskScore: 5,
    },
  },
  {
    key: 'pgEnvironmentalJusticeProxyDa',
    label: 'PG Environmental Justice Proxy (DA)',
    question: 'Which small areas show overlapping local burden, deprivation context, and adaptive-capacity gaps?',
    description:
      'CDC EJI-inspired local screen using module percentile-ranked sums. This is a local proxy, not the official ATSDR Environmental Justice Index.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['parks', 'heatShade', 'restaurants', 'census', 'bcAssessment', 'crime', 'transit', 'deprivation'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      cimdComposite: 18,
      cimdResidentialInstability: 8,
      cimdEconomicDependency: 10,
      cimdSituationalVulnerability: 12,
      populationDensity: 10,
      shadeGap: 18,
      crimePerCapita: 12,
      foodRiskScore: 8,
      criticalViolationRate: 6,
      buildingAge: 8,
      parkWalk10Access: 10,
      coolingWalk15Access: 10,
      accessibleFrequentTransitAccess: 8,
      serviceAccessComposite: 8,
    },
    methodSettings: MODULE_PERCENTILE_METHOD,
  },
  {
    key: 'pgSocialEnvironmentalRankDa',
    label: 'PG Social-Environmental Rank (DA)',
    question:
      'Which areas have overlapping social vulnerability and environmental burden, before health data is considered?',
    description:
      'EJI SER-style example that ranks social vulnerability and environmental burden modules, then combines those module ranks without health vulnerability.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['parks', 'heatShade', 'restaurants', 'census', 'bcAssessment', 'crime', 'transit', 'deprivation'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      cimdComposite: 18,
      cimdResidentialInstability: 8,
      cimdEconomicDependency: 10,
      populationDensity: 8,
      foodRiskScore: 10,
      criticalViolationRate: 8,
      crimePerCapita: 12,
      buildingAge: 8,
      parkWalk10Access: 10,
      serviceAccessComposite: 8,
    },
    methodSettings: MODULE_PERCENTILE_METHOD,
  },
  {
    key: 'pedestrianNetworkStudyMiDa',
    label: 'Pedestrian Network Study MI (DA)',
    question: 'Which small areas look strongest under a walkability equation inspired by the 2017 report?',
    description:
      'Adapts the report Mobility Index to the Index Lab boundary model using sidewalk/walkway density, crossings, transit, parks, childcare, POIs, and lower safety pressure.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['walkability', 'parks', 'transit'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      sidewalkDensity: 20,
      walkwayDensity: 12,
      walkabilityIntersectionDensity: 12,
      walkabilityCrossingDensity: 10,
      transitStopDensity: 10,
      parkWalk10Access: 10,
      childcareDensity: 8,
      walkabilityPoiDensity: 10,
      class3CrosswalkDensity: -4,
      pedestrianCrashDensity: -4,
    },
    methodSettings: PERCENTILE_METHOD,
  },
  {
    key: 'heatShadeNeedDa',
    label: 'Heat + Shade Need Proxy (DA)',
    question: 'Which small areas have higher heat adaptation need based on real shade and facility proxies?',
    description:
      'Uses the CityPG tree inventory, forest layers, community-facility proxies, building age, values, and population density. High scores mark areas needing closer heat/shade review.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['heatShade', 'census', 'bcAssessment'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      populationDensity: 22,
      buildingAge: 16,
      avgAssessedValue: -8,
      treeDensity: -16,
      matureTreeDensity: -12,
      forestAreaRatio: -18,
      coolingFacilityDensity: -8,
    },
    methodSettings: PERCENTILE_METHOD,
  },
  {
    key: 'shadeGapHeatMapDa',
    label: 'Shade Gap Heat Map (DA)',
    question: 'Where does a one-layer heat-map score show the largest shade and cooling gap?',
    description:
      'Uses the score builder heat-map lens as a score: high-ranking dissemination areas have lower canopy proxy and weaker cooling access.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['heatShade'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      shadeGap: 100,
    },
    methodSettings: PERCENTILE_METHOD,
  },
  {
    key: 'canopyCoolingHeatMapDa',
    label: 'Canopy + Cooling Heat Map (DA)',
    question: 'Which small areas look strongest for shade and cooling-service coverage?',
    description:
      'A compact heat-map score built from canopy proxy and cooling-facility access, useful as a positive heat-resilience layer.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['heatShade'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      canopyProxyRatio: 60,
      coolingWalk15Access: 40,
    },
    methodSettings: PERCENTILE_METHOD,
  },
  {
    key: 'sensorGapEquityDa',
    label: 'Sensor Gap + Equity Proxy (DA)',
    question: 'Where should PG prioritize new community air-quality monitors?',
    description:
      'Ranks populated areas with weaker monitor density, less network variety, and fewer nearby adaptive-capacity proxies.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['airQuality', 'parks', 'census'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      populationDensity: 28,
      overallDensity: -26,
      lowCostDensity: -18,
      referenceDensity: -16,
      networkVariety: -6,
      parkAreaRatio: -4,
      activeShare: -2,
    },
  },
  {
    key: 'schoolExposureMobilityDa',
    label: 'School Exposure + Active Mobility Proxy (DA)',
    question: 'Which areas look stronger for child-serving mobility and lower exposure pressure?',
    description:
      'A near-term school proxy using population, trails, parks, amenities, monitor coverage, food-risk, and safety pressure until school points and catchments are fully wired in.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['airQuality', 'parks', 'restaurants', 'census', 'crime'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      populationDensity: 18,
      parkDensity: 14,
      trailDensity: 16,
      amenityDensity: 10,
      overallDensity: -12,
      referenceDensity: -8,
      foodRiskScore: -8,
      criticalViolationRate: -6,
      crimePerCapita: -8,
    },
  },
  {
    key: 'housingAffordabilityDa',
    label: 'Housing Affordability (DA)',
    question: 'Which small areas combine lower assessed values with more housing choice?',
    description:
      'Uses BC Assessment parcels to balance lower values, multi-family share, parcel density, and recent value growth.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['bcAssessment', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      avgAssessedValue: -34,
      valueGrowth10y: -22,
      multiFamilyShare: 18,
      parcelDensity: 10,
      buildingAge: 8,
      populationDensity: 8,
    },
  },
  {
    key: 'redevelopmentPressureDa',
    label: 'Redevelopment Pressure (DA)',
    question: 'Where does PG show the strongest property redevelopment pressure?',
    description:
      'Highlights DAs with older buildings, high land-value share, vacant parcels, and rapid assessment growth.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['bcAssessment', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      valueGrowth10y: 28,
      landValueShare: 22,
      vacantParcelShare: 18,
      buildingAge: 14,
      commercialShare: 8,
      parcelDensity: 6,
      populationDensity: 4,
    },
  },
  {
    key: 'completeNeighbourhoodDa',
    label: 'Complete Neighbourhood (DA)',
    question: 'Which small neighbourhoods have the best mix of services, parks, housing, and safety?',
    description:
      'Combines food, parks, trails, housing mix, density, and crime per capita into a neighbourhood completeness score.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['restaurants', 'parks', 'bcAssessment', 'census', 'crime'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      restaurantDensity: 15,
      parkDensity: 12,
      trailDensity: 10,
      amenityDensity: 8,
      populationDensity: 12,
      parcelDensity: 8,
      multiFamilyShare: 8,
      foodRiskScore: -6,
      criticalViolationRate: -6,
      crimePerCapita: -15,
    },
  },
  {
    key: 'foodInspectionRiskDa',
    label: 'Food Inspection Risk (DA)',
    question: 'Which restaurant clusters have higher inspection risk?',
    description: 'Looks beyond hazard rating by adding critical violation rate and follow-up inspection rate.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['restaurants', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      criticalViolationRate: 34,
      followUpRate: 24,
      foodRiskScore: 22,
      restaurantDensity: 10,
      populationDensity: 10,
    },
  },
  {
    key: 'crimePressureDa',
    label: 'Crime Pressure (DA)',
    question: 'Where are incident counts high relative to area and population?',
    description:
      'Uses live PG crime points with census population to score density, per-capita risk, and recent activity.',
    boundarySource: 'census',
    boundaryLevel: 'da',
    dataSources: ['crime', 'census'],
    networkFilter: 'none',
    weights: {
      ...ZERO_WEIGHTS,
      crimeDensity: 35,
      crimePerCapita: 35,
      recentCrimeShare: 15,
      populationDensity: 15,
    },
  },

  // Census Subdivision (CSD) – 1 unit (city-wide), useful as a baseline
  {
    key: 'cityOverviewCsd',
    label: 'City Overview (CSD)',
    question: 'What is the overall livability score for Prince George as a municipality?',
    description: 'Single census subdivision view. Useful as a baseline to compare with finer-grained levels.',
    boundarySource: 'census',
    boundaryLevel: 'csd',
    dataSources: ['airQuality', 'parks', 'restaurants', 'census'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      parkAreaRatio: 15,
      parkDensity: 10,
      trailDensity: 10,
      restaurantDensity: 10,
      foodRiskScore: -10,
      overallDensity: 15,
      activeShare: 5,
      populationDensity: 10,
      amenityDensity: 8,
      networkVariety: 7,
    },
  },

  // ── Health Authority boundaries ──────────────────────────────────────

  // Health Authority (HA) – 5 regions, province-wide comparison
  {
    key: 'provincialAirQualityHa',
    label: 'Provincial Air Quality (HA)',
    question: "Which of BC's 5 health authorities has the best sensor coverage?",
    description:
      'Compares the 5 health authorities across BC by overall sensor density, network variety, and reference station coverage.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'healthAuthority',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      overallDensity: 30,
      referenceDensity: 25,
      lowCostDensity: 15,
      networkVariety: 14,
      parameterVariety: 6,
      activeShare: 10,
    },
  },

  // HSDA – 16 regions, sub-regional comparison
  {
    key: 'hsdaSensorCoverage',
    label: 'Sensor Coverage (HSDA)',
    question: 'Which health service delivery areas across BC have monitoring gaps?',
    description: 'Uses 16 HSDAs across BC. Reveals which sub-regions rely on community sensors vs. reference stations.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'hsda',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      overallDensity: 28,
      lowCostDensity: 18,
      referenceDensity: 22,
      networkVariety: 12,
      activeShare: 10,
      parameterVariety: 5,
      monitorCount: 5,
    },
  },

  // LHA – ~89 regions, local area comparison
  {
    key: 'lhaMonitoringComparison',
    label: 'Local Health Area Monitoring (LHA)',
    question: 'How does air quality monitoring compare across BC local health areas?',
    description: 'Compares ~89 LHAs across BC by sensor network coverage, variety, and active monitoring rates.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'lha',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      overallDensity: 35,
      lowCostDensity: 15,
      referenceDensity: 20,
      networkVariety: 12,
      parameterVariety: 6,
      activeShare: 8,
      monitorCount: 4,
    },
  },
  {
    key: 'lhaLowCostExpansion',
    label: 'Low-Cost Expansion Targets (LHA)',
    question: 'Which LHAs would benefit most from more PurpleAir/EGG community sensors?',
    description:
      'Prioritizes local health areas with low community sensor density but existing reference coverage. Low scores = best expansion targets.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'lha',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      lowCostDensity: 35,
      referenceDensity: -15,
      activeShare: 12,
      networkVariety: 15,
      parameterVariety: 8,
      overallDensity: 10,
      monitorCount: -5,
    },
  },

  // CHSA – ~200+ regions, community-level comparison
  {
    key: 'chsaSensorCoverage',
    label: 'Community Health Sensor Coverage (CHSA)',
    question: 'Which community health service areas across BC have the worst sensor coverage?',
    description:
      'The most granular health boundary level with ~200+ areas. Shows fine-grained provincial monitoring gaps.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'chsa',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      overallDensity: 30,
      lowCostDensity: 20,
      referenceDensity: 18,
      networkVariety: 10,
      activeShare: 10,
      parameterVariety: 5,
      monitorCount: 7,
    },
  },
  {
    key: 'chsaReferenceGaps',
    label: 'Reference Station Gaps (CHSA)',
    question: 'Which community areas lack government-grade reference monitoring?',
    description:
      'Highlights CHSAs that rely entirely on community sensors with no reference stations. Low scores = regulatory monitoring gaps.',
    boundarySource: 'bcHealth',
    boundaryLevel: 'chsa',
    dataSources: ['airQuality'],
    networkFilter: 'all',
    weights: {
      ...ZERO_WEIGHTS,
      referenceDensity: 45,
      overallDensity: 15,
      activeShare: 15,
      parameterVariety: 10,
      networkVariety: 8,
      monitorCount: 7,
    },
  },
]

function getRecommendedExampleMethodSettings(example: ScoreExample): Partial<ScoreMethodSettings> {
  if (example.key.toLowerCase().includes('redevelopment')) return Z_SCORE_METHOD
  const airOnly = example.dataSources.length === 1 && example.dataSources[0] === 'airQuality'
  const monitoringGap = /gap|sensor|monitor|air quality/i.test(`${example.label} ${example.question}`)
  if (airOnly || monitoringGap) return WINSORIZED_METHOD
  return PERCENTILE_METHOD
}

export const SCORE_BUILDER_EXAMPLES: ScoreExample[] = SCORE_EXAMPLES.map((example) => ({
  ...example,
  methodSettings: example.methodSettings ?? getRecommendedExampleMethodSettings(example),
})).filter(
  (example) =>
    example.boundarySource === 'cityCommunity' ||
    (example.boundarySource === 'census' && (example.boundaryLevel === 'ct' || example.boundaryLevel === 'da')) ||
    example.boundarySource === 'bcHealth',
)
