import type {
  ScoreIndexDomain,
  ScoreIndexModule,
  ScoreMetricValueBehavior,
  ScoreMissingDataPolicy,
  ScoreMetricDefinition,
  ScoreMetricDirection,
  ScoreMetricComponent,
  ScoreMetricKey,
  ScoreSpatialMethod,
  ScoreUncertaintyLevel,
} from '../types'

type ScoreMetricBaseDefinition = Omit<
  ScoreMetricDefinition,
  | 'direction'
  | 'component'
  | 'dataSourceLabel'
  | 'spatialMethod'
  | 'uncertainty'
  | 'caveat'
  | 'directionLabel'
  | 'sourceUrl'
  | 'freshnessLabel'
  | 'comparisonBasis'
  | 'indexModule'
  | 'indexDomain'
  | 'valueBehavior'
  | 'missingDataPolicy'
  | 'proxyLevel'
>

export const SCORE_ACCESS_THRESHOLD_METRICS: ScoreMetricKey[] = [
  'parkWalk10Access',
  'parkWalk20Access',
  'coolingWalk15Access',
  'parkTransit20Access',
  'serviceAccessComposite',
  'frequentTransitStopAccess',
  'accessibleFrequentTransitAccess',
]

const SCORE_METRIC_BASES: ScoreMetricBaseDefinition[] = [
  // Air Quality
  {
    key: 'overallDensity',
    label: 'Overall Sensor Density',
    shortLabel: 'Overall density',
    description: 'Total sensors per km² inside each boundary.',
    format: 'density',
    category: 'airQuality',
  },
  {
    key: 'lowCostDensity',
    label: 'Low-Cost Sensor Density',
    shortLabel: 'Low-cost density',
    description: 'Low-cost network sensors (PA + EGG) per km².',
    format: 'density',
    category: 'airQuality',
  },
  {
    key: 'referenceDensity',
    label: 'Reference Sensor Density',
    shortLabel: 'Reference density',
    description: 'Regulatory and non-low-cost sensors per km².',
    format: 'density',
    category: 'airQuality',
  },
  {
    key: 'networkVariety',
    label: 'Network Variety',
    shortLabel: 'Network variety',
    description: 'Unique monitoring networks represented in a boundary.',
    format: 'count',
    category: 'airQuality',
  },
  {
    key: 'parameterVariety',
    label: 'Parameter Variety',
    shortLabel: 'Parameter variety',
    description: 'Unique parameter labels observed among sensors.',
    format: 'count',
    category: 'airQuality',
  },
  {
    key: 'activeShare',
    label: 'Active Sensor Share',
    shortLabel: 'Active share',
    description: 'Share of in-boundary sensors marked active.',
    format: 'ratio',
    category: 'airQuality',
  },
  {
    key: 'monitorCount',
    label: 'Raw Sensor Count',
    shortLabel: 'Sensor count',
    description: 'Absolute number of sensors in each boundary.',
    format: 'count',
    category: 'airQuality',
  },
  // Parks & Recreation
  {
    key: 'parkDensity',
    label: 'Park Density',
    shortLabel: 'Park density',
    description: 'Number of parks per km² in each boundary.',
    format: 'density',
    category: 'parksRec',
  },
  {
    key: 'parkAreaRatio',
    label: 'Park Area Ratio',
    shortLabel: 'Park area %',
    description: 'Percentage of boundary area covered by parks.',
    format: 'percent',
    category: 'parksRec',
  },
  {
    key: 'trailDensity',
    label: 'Trail Density',
    shortLabel: 'Trail density',
    description: 'Trail km per km² in each boundary.',
    format: 'density',
    category: 'parksRec',
  },
  {
    key: 'amenityDensity',
    label: 'Amenity Density',
    shortLabel: 'Amenity density',
    description: 'Park amenities per km² in each boundary.',
    format: 'density',
    category: 'parksRec',
  },
  {
    key: 'parkAccessGap1Mile',
    label: 'Park Access Gap',
    shortLabel: 'Park gap',
    description: 'Share of boundary area outside a 1.6 km buffer around CityPG park/open-space polygons.',
    format: 'percent',
    category: 'parksRec',
  },
  // Heat & Shade
  {
    key: 'treeDensity',
    label: 'Tree Density',
    shortLabel: 'Tree density',
    description: 'Tree points per km² inside each boundary, where available.',
    format: 'density',
    category: 'heatShade',
  },
  {
    key: 'matureTreeDensity',
    label: 'Mature Tree Density',
    shortLabel: 'Mature trees',
    description: 'Mature tree points per km² inside each boundary, where available.',
    format: 'density',
    category: 'heatShade',
  },
  {
    key: 'forestAreaRatio',
    label: 'Forest Area Ratio',
    shortLabel: 'Forest area %',
    description: 'Share of boundary area covered by forest/open-space canopy proxies, where available.',
    format: 'percent',
    category: 'heatShade',
  },
  {
    key: 'coolingFacilityDensity',
    label: 'Cooling Facility Density',
    shortLabel: 'Cooling facilities',
    description: 'Cooling or community facility points per km² inside each boundary, where available.',
    format: 'density',
    category: 'heatShade',
  },
  {
    key: 'responseFacilityDensity',
    label: 'Response Facility Density',
    shortLabel: 'Response facilities',
    description: 'Emergency response or support facility points per km² inside each boundary, where available.',
    format: 'density',
    category: 'heatShade',
  },
  // Food Safety
  {
    key: 'restaurantDensity',
    label: 'Restaurant Density',
    shortLabel: 'Restaurant density',
    description: 'Restaurants per km² in each boundary.',
    format: 'density',
    category: 'foodSafety',
  },
  {
    key: 'foodRiskScore',
    label: 'Food Risk Score',
    shortLabel: 'Food risk',
    description: 'Average hazard level of food facilities (0=Low, 1=High).',
    format: 'ratio',
    category: 'foodSafety',
  },
  {
    key: 'criticalViolationRate',
    label: 'Critical Violation Rate',
    shortLabel: 'Critical rate',
    description: 'Critical violations per inspection for restaurants in each boundary.',
    format: 'ratio',
    category: 'foodSafety',
  },
  {
    key: 'followUpRate',
    label: 'Follow-Up Inspection Rate',
    shortLabel: 'Follow-up rate',
    description: 'Share of inspections that required a follow-up.',
    format: 'ratio',
    category: 'foodSafety',
  },
  // Demographics
  {
    key: 'populationDensity',
    label: 'Population Density',
    shortLabel: 'Pop. density',
    description: 'Census population per km² from direct census-boundary population where available, falling back to overlapping DA centroids.',
    format: 'density',
    category: 'demographics',
  },
  // Property & Housing
  {
    key: 'parcelDensity',
    label: 'Parcel Density',
    shortLabel: 'Parcel density',
    description: 'BC Assessment parcels per km².',
    format: 'density',
    category: 'property',
  },
  {
    key: 'avgAssessedValue',
    label: 'Average Assessed Value',
    shortLabel: 'Avg. value',
    description: 'Average total assessed parcel value.',
    format: 'currency',
    category: 'property',
  },
  {
    key: 'valueGrowth10y',
    label: '10-Year Value Growth',
    shortLabel: '10y growth',
    description: 'Average parcel value growth across available assessment history.',
    format: 'percent',
    category: 'property',
  },
  {
    key: 'buildingAge',
    label: 'Average Building Age',
    shortLabel: 'Building age',
    description: 'Average age of parcels with a known year built.',
    format: 'years',
    category: 'property',
  },
  {
    key: 'pre1980HousingShare',
    label: 'Pre-1980 Housing Share',
    shortLabel: 'Pre-1980',
    description: 'Share of BC Assessment parcels with known building year before 1980.',
    format: 'percent',
    category: 'property',
  },
  {
    key: 'vacantParcelShare',
    label: 'Vacant Parcel Share',
    shortLabel: 'Vacant share',
    description: 'Share of parcels classified as vacant.',
    format: 'percent',
    category: 'property',
  },
  {
    key: 'multiFamilyShare',
    label: 'Multi-Family Share',
    shortLabel: 'Multi-family',
    description: 'Share of parcels classified as multi-family.',
    format: 'percent',
    category: 'property',
  },
  {
    key: 'commercialShare',
    label: 'Commercial Parcel Share',
    shortLabel: 'Commercial',
    description: 'Share of parcels classified as commercial.',
    format: 'percent',
    category: 'property',
  },
  {
    key: 'landValueShare',
    label: 'Land Value Share',
    shortLabel: 'Land value',
    description: 'Share of assessed value assigned to land rather than buildings.',
    format: 'percent',
    category: 'property',
  },
  // Safety
  {
    key: 'crimeDensity',
    label: 'Crime Density',
    shortLabel: 'Crime density',
    description: 'Crime incidents per km².',
    format: 'density',
    category: 'safety',
  },
  {
    key: 'crimePerCapita',
    label: 'Crime Per Capita',
    shortLabel: 'Crime/capita',
    description: 'Crime incidents per resident based on census population.',
    format: 'ratio',
    category: 'safety',
  },
  {
    key: 'recentCrimeShare',
    label: 'Recent Crime Share',
    shortLabel: 'Recent crime',
    description: 'Share of incidents from the most recent 180 days in the loaded data.',
    format: 'percent',
    category: 'safety',
  },
  // Transit
  {
    key: 'transitStopDensity',
    label: 'Transit Stop Density',
    shortLabel: 'Transit density',
    description: 'Transit stops per km² inside each boundary.',
    format: 'density',
    category: 'transit',
  },
  {
    key: 'accessibleTransitStopDensity',
    label: 'Accessible Transit Stop Density',
    shortLabel: 'Accessible transit',
    description: 'Accessible transit stops per km² inside each boundary.',
    format: 'density',
    category: 'transit',
  },
  {
    key: 'transitShelterDensity',
    label: 'Transit Shelter/Exchange Density',
    shortLabel: 'Shelter density',
    description: 'Transit shelters and exchanges per km² inside each boundary.',
    format: 'density',
    category: 'transit',
  },
  {
    key: 'frequentTransitStopAccess',
    label: 'Frequent Transit Stop Access',
    shortLabel: 'Frequent transit',
    description: 'Share of regional demand within an estimated 10-minute walk of stops with stronger weekday service.',
    format: 'percent',
    category: 'transit',
  },
  {
    key: 'transitServiceSpan',
    label: 'Transit Service Span',
    shortLabel: 'Service span',
    description: 'Average daily service span in hours for in-boundary or nearby GTFS stops.',
    format: 'count',
    category: 'transit',
  },
  {
    key: 'transitTripsPerStop',
    label: 'Transit Trips per Stop',
    shortLabel: 'Trips/stop',
    description: 'Average scheduled weekday stop events per in-boundary stop.',
    format: 'count',
    category: 'transit',
  },
  {
    key: 'accessibleFrequentTransitAccess',
    label: 'Accessible Frequent Transit Access',
    shortLabel: 'Accessible frequent',
    description: 'Share of regional demand within an estimated 10-minute walk of accessible frequent-service stops.',
    format: 'percent',
    category: 'transit',
  },
  // Walkability / Pedestrian Network Study
  {
    key: 'sidewalkDensity',
    label: 'Sidewalk Density',
    shortLabel: 'Sidewalk density',
    description: 'Sidewalk kilometres per km² from CityPG pedestrian infrastructure.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'walkwayDensity',
    label: 'Walkway Density',
    shortLabel: 'Walkway density',
    description: 'Walkway/path kilometres per km² from CityPG pedestrian infrastructure.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'walkabilityIntersectionDensity',
    label: 'Intersection Density',
    shortLabel: 'Intersections',
    description: 'Road intersections per km², a street-connectivity proxy for walkability.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'walkabilityCrossingDensity',
    label: 'Pedestrian Crossing Density',
    shortLabel: 'Crossings',
    description: 'Mapped pedestrian crossings per km² from OSM and report supplemental layers.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'childcareDensity',
    label: 'Childcare / Daycare Density',
    shortLabel: 'Childcare',
    description: 'Childcare/daycare points per km² used as the C0 report factor proxy.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'walkabilityPoiDensity',
    label: 'Supplemental POI Density',
    shortLabel: 'Walk POIs',
    description: 'Supplemental housing, entertainment, and intercity-service POIs per km².',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'class3CrosswalkDensity',
    label: 'Class-3 Crosswalk Pressure',
    shortLabel: 'Class-3 xwalk',
    description: 'Report class-3 crosswalk locations per km²; higher values indicate more upgrade pressure.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'pedestrianCrashDensity',
    label: 'Pedestrian Crash Density',
    shortLabel: 'Ped crashes',
    description: 'ICBC pedestrian-crash concentration per km² where mapped crash summaries are available.',
    format: 'density',
    category: 'walkability',
  },
  {
    key: 'communityWalkBalanced',
    label: 'Community Walkability (Balanced)',
    shortLabel: 'Walk balanced',
    description: 'Precomputed balanced community walkability score. Only populated on the Community polygons boundary.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'communityWalkInfrastructure',
    label: 'Community Walkability (Infrastructure)',
    shortLabel: 'Walk infra',
    description: 'Precomputed infrastructure-weighted community walkability score. Community polygons boundary only.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'communityWalkAccess',
    label: 'Community Walkability (Access)',
    shortLabel: 'Walk access',
    description: 'Precomputed access-weighted community walkability score. Community polygons boundary only.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'communityWalkSafetyAdjusted',
    label: 'Community Walkability (Safety-adjusted)',
    shortLabel: 'Walk safety',
    description: 'Precomputed safety-adjusted community walkability score. Community polygons boundary only.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'communityWalkSupplementedLocal',
    label: 'Community Walkability (Supplemented local)',
    shortLabel: 'Walk supp.',
    description: 'Precomputed supplemented-local community walkability score. Community polygons boundary only.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'walkabilityMiSurface',
    label: 'Walkability MI Surface (mean band)',
    shortLabel: 'MI surface',
    description: 'Mean Mobility Index band (1-5) of the citywide walkability raster cells inside each area.',
    format: 'count',
    category: 'walkability',
  },
  {
    key: 'parkWalk10Access',
    label: '10-Minute Park Walk Access',
    shortLabel: 'Park 10-min',
    description: 'Distance-decay estimate of park access within a 10-minute walk catchment.',
    format: 'percent',
    category: 'parksRec',
  },
  {
    key: 'parkWalk20Access',
    label: '20-Minute Park Walk Access',
    shortLabel: 'Park 20-min',
    description: 'Distance-decay estimate of park access within a 20-minute walk catchment.',
    format: 'percent',
    category: 'parksRec',
  },
  {
    key: 'coolingWalk15Access',
    label: '15-Minute Cooling Access',
    shortLabel: 'Cooling 15-min',
    description: 'Distance-decay estimate of cooling/community facility access within a 15-minute walk catchment.',
    format: 'percent',
    category: 'heatShade',
  },
  {
    key: 'parkTransit20Access',
    label: '20-Minute Park Transit Access',
    shortLabel: 'Park transit',
    description: 'Catchment estimate for park access where nearby transit service improves reach.',
    format: 'percent',
    category: 'parksRec',
  },
  {
    key: 'serviceAccessComposite',
    label: 'Service Access Composite',
    shortLabel: 'Service access',
    description: 'Combined catchment estimate for parks, cooling facilities, amenities, and transit.',
    format: 'percent',
    category: 'transit',
  },
  {
    key: 'canopyProxyRatio',
    label: 'Canopy Proxy Ratio',
    shortLabel: 'Canopy proxy',
    description: 'Tree-inventory buffer and forest/open-space proxy area as a share of boundary area.',
    format: 'percent',
    category: 'heatShade',
  },
  {
    key: 'shadeGap',
    label: 'Shade Gap',
    shortLabel: 'Shade gap',
    description: 'Need proxy combining low canopy/cooling access with population and deprivation pressure.',
    format: 'percent',
    category: 'heatShade',
  },
  {
    key: 'cimdComposite',
    label: 'CIMD Composite Deprivation',
    shortLabel: 'CIMD composite',
    description: 'Statistics Canada Canadian Index of Multiple Deprivation composite context.',
    format: 'percent',
    category: 'deprivation',
  },
  {
    key: 'cimdResidentialInstability',
    label: 'CIMD Residential Instability',
    shortLabel: 'Residential instability',
    description: 'CIMD residential instability dimension.',
    format: 'percent',
    category: 'deprivation',
  },
  {
    key: 'cimdEconomicDependency',
    label: 'CIMD Economic Dependency',
    shortLabel: 'Economic dependency',
    description: 'CIMD economic dependency dimension.',
    format: 'percent',
    category: 'deprivation',
  },
  {
    key: 'cimdSituationalVulnerability',
    label: 'CIMD Situational Vulnerability',
    shortLabel: 'Situational vulnerability',
    description: 'CIMD situational vulnerability dimension.',
    format: 'percent',
    category: 'deprivation',
  },
  {
    key: 'cimdEthnoCulturalComposition',
    label: 'CIMD Ethno-Cultural Composition',
    shortLabel: 'Ethno-cultural',
    description: 'CIMD ethno-cultural composition dimension.',
    format: 'percent',
    category: 'deprivation',
  },
  {
    key: 'healthyFoodOutletAccess1km',
    label: 'Healthy Food Outlet Access',
    shortLabel: 'Healthy food',
    description: 'Healthy food outlet candidates within 1 km of the boundary centroid.',
    format: 'count',
    category: 'healthyPlanPg',
  },
  {
    key: 'retailServiceAccess1km',
    label: 'Retail/Service Access',
    shortLabel: 'Retail/services',
    description: 'Retail and daily-service POIs within 1 km of the boundary centroid.',
    format: 'count',
    category: 'healthyPlanPg',
  },
  {
    key: 'educationFacilityAccess1km',
    label: 'Education Facility Access',
    shortLabel: 'Education',
    description: 'K-12, childcare, and post-secondary facilities within 1 km of the boundary centroid.',
    format: 'count',
    category: 'healthyPlanPg',
  },
  {
    key: 'geocodedBusinessDensity',
    label: 'Geocoded Business Density',
    shortLabel: 'Businesses',
    description: 'CityPG business licence records geocoded by BC Address Geocoder per km².',
    format: 'density',
    category: 'healthyPlanPg',
  },
]

const METRIC_DIRECTION: Record<ScoreMetricKey, ScoreMetricDirection> = {
  overallDensity: 'higherIsBetter',
  lowCostDensity: 'higherIsBetter',
  referenceDensity: 'higherIsBetter',
  networkVariety: 'higherIsBetter',
  parameterVariety: 'higherIsBetter',
  activeShare: 'higherIsBetter',
  monitorCount: 'higherIsBetter',
  parkDensity: 'higherIsBetter',
  parkAreaRatio: 'higherIsBetter',
  trailDensity: 'higherIsBetter',
  amenityDensity: 'higherIsBetter',
  parkAccessGap1Mile: 'higherIsWorse',
  treeDensity: 'higherIsBetter',
  matureTreeDensity: 'higherIsBetter',
  forestAreaRatio: 'higherIsBetter',
  coolingFacilityDensity: 'higherIsBetter',
  responseFacilityDensity: 'higherIsBetter',
  restaurantDensity: 'higherIsBetter',
  foodRiskScore: 'higherIsWorse',
  criticalViolationRate: 'higherIsWorse',
  followUpRate: 'higherIsWorse',
  populationDensity: 'higherIsWorse',
  parcelDensity: 'higherIsBetter',
  avgAssessedValue: 'higherIsBetter',
  valueGrowth10y: 'higherIsWorse',
  buildingAge: 'higherIsWorse',
  pre1980HousingShare: 'higherIsWorse',
  vacantParcelShare: 'higherIsWorse',
  multiFamilyShare: 'higherIsBetter',
  commercialShare: 'higherIsBetter',
  landValueShare: 'higherIsWorse',
  crimeDensity: 'higherIsWorse',
  crimePerCapita: 'higherIsWorse',
  recentCrimeShare: 'higherIsWorse',
  transitStopDensity: 'higherIsBetter',
  accessibleTransitStopDensity: 'higherIsBetter',
  transitShelterDensity: 'higherIsBetter',
  frequentTransitStopAccess: 'higherIsBetter',
  transitServiceSpan: 'higherIsBetter',
  transitTripsPerStop: 'higherIsBetter',
  accessibleFrequentTransitAccess: 'higherIsBetter',
  sidewalkDensity: 'higherIsBetter',
  walkwayDensity: 'higherIsBetter',
  walkabilityIntersectionDensity: 'higherIsBetter',
  walkabilityCrossingDensity: 'higherIsBetter',
  childcareDensity: 'higherIsBetter',
  walkabilityPoiDensity: 'higherIsBetter',
  class3CrosswalkDensity: 'higherIsWorse',
  pedestrianCrashDensity: 'higherIsWorse',
  communityWalkBalanced: 'higherIsBetter',
  communityWalkInfrastructure: 'higherIsBetter',
  communityWalkAccess: 'higherIsBetter',
  communityWalkSafetyAdjusted: 'higherIsBetter',
  communityWalkSupplementedLocal: 'higherIsBetter',
  walkabilityMiSurface: 'higherIsBetter',
  parkWalk10Access: 'higherIsBetter',
  parkWalk20Access: 'higherIsBetter',
  coolingWalk15Access: 'higherIsBetter',
  parkTransit20Access: 'higherIsBetter',
  serviceAccessComposite: 'higherIsBetter',
  canopyProxyRatio: 'higherIsBetter',
  shadeGap: 'higherIsWorse',
  cimdComposite: 'higherIsWorse',
  cimdResidentialInstability: 'higherIsWorse',
  cimdEconomicDependency: 'higherIsWorse',
  cimdSituationalVulnerability: 'higherIsWorse',
  cimdEthnoCulturalComposition: 'higherIsWorse',
  healthyFoodOutletAccess1km: 'higherIsBetter',
  retailServiceAccess1km: 'higherIsBetter',
  educationFacilityAccess1km: 'higherIsBetter',
  geocodedBusinessDensity: 'higherIsBetter',
}

const METRIC_COMPONENT: Record<ScoreMetricKey, ScoreMetricComponent> = {
  overallDensity: 'monitoringAdequacy',
  lowCostDensity: 'monitoringAdequacy',
  referenceDensity: 'monitoringAdequacy',
  networkVariety: 'monitoringAdequacy',
  parameterVariety: 'monitoringAdequacy',
  activeShare: 'monitoringAdequacy',
  monitorCount: 'monitoringAdequacy',
  parkDensity: 'adaptiveCapacity',
  parkAreaRatio: 'adaptiveCapacity',
  trailDensity: 'serviceAccess',
  amenityDensity: 'serviceAccess',
  parkAccessGap1Mile: 'environmentalBurden',
  treeDensity: 'adaptiveCapacity',
  matureTreeDensity: 'adaptiveCapacity',
  forestAreaRatio: 'adaptiveCapacity',
  coolingFacilityDensity: 'adaptiveCapacity',
  responseFacilityDensity: 'adaptiveCapacity',
  restaurantDensity: 'serviceAccess',
  foodRiskScore: 'environmentalBurden',
  criticalViolationRate: 'environmentalBurden',
  followUpRate: 'environmentalBurden',
  populationDensity: 'sensitivity',
  parcelDensity: 'housingPressure',
  avgAssessedValue: 'housingPressure',
  valueGrowth10y: 'housingPressure',
  buildingAge: 'housingPressure',
  pre1980HousingShare: 'housingPressure',
  vacantParcelShare: 'housingPressure',
  multiFamilyShare: 'adaptiveCapacity',
  commercialShare: 'serviceAccess',
  landValueShare: 'housingPressure',
  crimeDensity: 'safetyPressure',
  crimePerCapita: 'safetyPressure',
  recentCrimeShare: 'safetyPressure',
  transitStopDensity: 'serviceAccess',
  accessibleTransitStopDensity: 'serviceAccess',
  transitShelterDensity: 'adaptiveCapacity',
  frequentTransitStopAccess: 'serviceAccess',
  transitServiceSpan: 'serviceAccess',
  transitTripsPerStop: 'serviceAccess',
  accessibleFrequentTransitAccess: 'serviceAccess',
  sidewalkDensity: 'serviceAccess',
  walkwayDensity: 'serviceAccess',
  walkabilityIntersectionDensity: 'serviceAccess',
  walkabilityCrossingDensity: 'serviceAccess',
  childcareDensity: 'serviceAccess',
  walkabilityPoiDensity: 'serviceAccess',
  class3CrosswalkDensity: 'safetyPressure',
  pedestrianCrashDensity: 'safetyPressure',
  communityWalkBalanced: 'serviceAccess',
  communityWalkInfrastructure: 'serviceAccess',
  communityWalkAccess: 'serviceAccess',
  communityWalkSafetyAdjusted: 'serviceAccess',
  communityWalkSupplementedLocal: 'serviceAccess',
  walkabilityMiSurface: 'serviceAccess',
  parkWalk10Access: 'serviceAccess',
  parkWalk20Access: 'serviceAccess',
  coolingWalk15Access: 'adaptiveCapacity',
  parkTransit20Access: 'serviceAccess',
  serviceAccessComposite: 'serviceAccess',
  canopyProxyRatio: 'adaptiveCapacity',
  shadeGap: 'environmentalBurden',
  cimdComposite: 'sensitivity',
  cimdResidentialInstability: 'sensitivity',
  cimdEconomicDependency: 'sensitivity',
  cimdSituationalVulnerability: 'sensitivity',
  cimdEthnoCulturalComposition: 'sensitivity',
  healthyFoodOutletAccess1km: 'serviceAccess',
  retailServiceAccess1km: 'serviceAccess',
  educationFacilityAccess1km: 'serviceAccess',
  geocodedBusinessDensity: 'serviceAccess',
}

const METRIC_SPATIAL_METHOD: Record<ScoreMetricKey, ScoreSpatialMethod> = {
  overallDensity: 'pointInPolygon',
  lowCostDensity: 'pointInPolygon',
  referenceDensity: 'pointInPolygon',
  networkVariety: 'pointInPolygon',
  parameterVariety: 'pointInPolygon',
  activeShare: 'pointInPolygon',
  monitorCount: 'pointInPolygon',
  parkDensity: 'centroidInPolygon',
  parkAreaRatio: 'centroidInPolygon',
  trailDensity: 'midpointInPolygon',
  amenityDensity: 'pointInPolygon',
  parkAccessGap1Mile: 'bufferAreaIntersection',
  treeDensity: 'pointInPolygon',
  matureTreeDensity: 'pointInPolygon',
  forestAreaRatio: 'derivedRatio',
  coolingFacilityDensity: 'pointInPolygon',
  responseFacilityDensity: 'pointInPolygon',
  restaurantDensity: 'pointInPolygon',
  foodRiskScore: 'pointInPolygon',
  criticalViolationRate: 'pointInPolygon',
  followUpRate: 'pointInPolygon',
  populationDensity: 'centroidInPolygon',
  parcelDensity: 'directBoundaryJoin',
  avgAssessedValue: 'directBoundaryJoin',
  valueGrowth10y: 'directBoundaryJoin',
  buildingAge: 'directBoundaryJoin',
  pre1980HousingShare: 'directBoundaryJoin',
  vacantParcelShare: 'directBoundaryJoin',
  multiFamilyShare: 'directBoundaryJoin',
  commercialShare: 'directBoundaryJoin',
  landValueShare: 'directBoundaryJoin',
  crimeDensity: 'pointInPolygon',
  crimePerCapita: 'pointInPolygon',
  recentCrimeShare: 'pointInPolygon',
  transitStopDensity: 'pointInPolygon',
  accessibleTransitStopDensity: 'pointInPolygon',
  transitShelterDensity: 'pointInPolygon',
  frequentTransitStopAccess: 'derivedRatio',
  transitServiceSpan: 'pointInPolygon',
  transitTripsPerStop: 'pointInPolygon',
  accessibleFrequentTransitAccess: 'derivedRatio',
  sidewalkDensity: 'midpointInPolygon',
  walkwayDensity: 'midpointInPolygon',
  walkabilityIntersectionDensity: 'pointInPolygon',
  walkabilityCrossingDensity: 'pointInPolygon',
  childcareDensity: 'pointInPolygon',
  walkabilityPoiDensity: 'pointInPolygon',
  class3CrosswalkDensity: 'pointInPolygon',
  pedestrianCrashDensity: 'pointInPolygon',
  communityWalkBalanced: 'directBoundaryJoin',
  communityWalkInfrastructure: 'directBoundaryJoin',
  communityWalkAccess: 'directBoundaryJoin',
  communityWalkSafetyAdjusted: 'directBoundaryJoin',
  communityWalkSupplementedLocal: 'directBoundaryJoin',
  walkabilityMiSurface: 'pointInPolygon',
  parkWalk10Access: 'derivedRatio',
  parkWalk20Access: 'derivedRatio',
  coolingWalk15Access: 'derivedRatio',
  parkTransit20Access: 'derivedRatio',
  serviceAccessComposite: 'derivedRatio',
  canopyProxyRatio: 'derivedRatio',
  shadeGap: 'derivedRatio',
  cimdComposite: 'directBoundaryJoin',
  cimdResidentialInstability: 'directBoundaryJoin',
  cimdEconomicDependency: 'directBoundaryJoin',
  cimdSituationalVulnerability: 'directBoundaryJoin',
  cimdEthnoCulturalComposition: 'directBoundaryJoin',
  healthyFoodOutletAccess1km: 'derivedRatio',
  retailServiceAccess1km: 'derivedRatio',
  educationFacilityAccess1km: 'derivedRatio',
  geocodedBusinessDensity: 'pointInPolygon',
}

const METRIC_UNCERTAINTY: Record<ScoreMetricKey, ScoreUncertaintyLevel> = {
  overallDensity: 'medium',
  lowCostDensity: 'medium',
  referenceDensity: 'low',
  networkVariety: 'medium',
  parameterVariety: 'medium',
  activeShare: 'medium',
  monitorCount: 'medium',
  parkDensity: 'medium',
  parkAreaRatio: 'high',
  trailDensity: 'medium',
  amenityDensity: 'medium',
  parkAccessGap1Mile: 'medium',
  treeDensity: 'high',
  matureTreeDensity: 'high',
  forestAreaRatio: 'high',
  coolingFacilityDensity: 'high',
  responseFacilityDensity: 'medium',
  restaurantDensity: 'medium',
  foodRiskScore: 'medium',
  criticalViolationRate: 'medium',
  followUpRate: 'medium',
  populationDensity: 'medium',
  parcelDensity: 'low',
  avgAssessedValue: 'low',
  valueGrowth10y: 'medium',
  buildingAge: 'medium',
  pre1980HousingShare: 'medium',
  vacantParcelShare: 'medium',
  multiFamilyShare: 'medium',
  commercialShare: 'medium',
  landValueShare: 'medium',
  crimeDensity: 'high',
  crimePerCapita: 'high',
  recentCrimeShare: 'high',
  transitStopDensity: 'medium',
  accessibleTransitStopDensity: 'medium',
  transitShelterDensity: 'medium',
  frequentTransitStopAccess: 'medium',
  transitServiceSpan: 'medium',
  transitTripsPerStop: 'medium',
  accessibleFrequentTransitAccess: 'medium',
  sidewalkDensity: 'medium',
  walkwayDensity: 'medium',
  walkabilityIntersectionDensity: 'medium',
  walkabilityCrossingDensity: 'medium',
  childcareDensity: 'medium',
  walkabilityPoiDensity: 'high',
  class3CrosswalkDensity: 'medium',
  pedestrianCrashDensity: 'high',
  communityWalkBalanced: 'low',
  communityWalkInfrastructure: 'low',
  communityWalkAccess: 'low',
  communityWalkSafetyAdjusted: 'low',
  communityWalkSupplementedLocal: 'low',
  walkabilityMiSurface: 'medium',
  parkWalk10Access: 'high',
  parkWalk20Access: 'high',
  coolingWalk15Access: 'high',
  parkTransit20Access: 'high',
  serviceAccessComposite: 'high',
  canopyProxyRatio: 'high',
  shadeGap: 'high',
  cimdComposite: 'medium',
  cimdResidentialInstability: 'medium',
  cimdEconomicDependency: 'medium',
  cimdSituationalVulnerability: 'medium',
  cimdEthnoCulturalComposition: 'medium',
  healthyFoodOutletAccess1km: 'high',
  retailServiceAccess1km: 'high',
  educationFacilityAccess1km: 'low',
  geocodedBusinessDensity: 'medium',
}

const METRIC_CAVEATS: Partial<Record<ScoreMetricKey, string>> = {
  parkAreaRatio: 'Uses park centroid assignment, so parks crossing a boundary are not area-weighted yet.',
  parkAccessGap1Mile:
    'Uses CityPG park/open-space polygons buffered by 1.6 km; it is an area-access screen, not a sidewalk-network walking-time model.',
  trailDensity: 'Uses trail midpoint assignment rather than network-length clipping by boundary.',
  treeDensity: 'Tree inventory coverage varies by source and is not a full canopy model.',
  matureTreeDensity: 'Maturity classification depends on source attributes and may be incomplete.',
  forestAreaRatio: 'Forest/open-space proxy is not a remote-sensing canopy or shade-quality layer.',
  coolingFacilityDensity: 'Cooling facility inventory is a proxy until verified public cooling-centre data is loaded.',
  populationDensity: 'Uses direct census-boundary population for loaded census polygons, including DB records with the DB-to-CHSA crosswalk; non-census boundaries still use DA centroid assignment.',
  crimeDensity: 'Live point data can shift over time and should be interpreted as planning context, not official risk.',
  crimePerCapita: 'Combines live incidents with census population, so temporal alignment is approximate.',
  recentCrimeShare: 'Recent window is relative to the newest loaded incident date.',
  transitStopDensity:
    'Uses CityPG/BC Transit stop point inventory; route frequency and service span are not included yet.',
  accessibleTransitStopDensity: 'Uses the stop inventory Accessible flag, where populated.',
  transitShelterDensity:
    'Counts shelter and exchange subtype points; benches, lighting, and sidewalk flags are separate attributes.',
  frequentTransitStopAccess: 'Catchment accessibility estimate; not a network-certified travel-time model.',
  accessibleFrequentTransitAccess: 'Catchment accessibility estimate; depends on stop accessibility flags/proxies.',
  parkWalk10Access: 'Distance-decay catchment estimate; not a sidewalk-network travel-time model.',
  parkWalk20Access: 'Distance-decay catchment estimate; not a sidewalk-network travel-time model.',
  coolingWalk15Access:
    'Cooling/community facility inventory is a proxy until verified public cooling-centre data is loaded.',
  parkTransit20Access: 'Transit-assisted park access is estimated from nearby service, not full itinerary planning.',
  serviceAccessComposite: 'Composite catchment estimate; review component metrics before making site decisions.',
  sidewalkDensity: 'Line lengths use midpoint assignment to the selected boundary and are not split at boundary edges.',
  walkwayDensity: 'Line lengths use midpoint assignment to the selected boundary and are not split at boundary edges.',
  walkabilityCrossingDensity:
    'Crossing inventory combines public-data/reconstructed layers and may not match the 2017 geodatabase exactly.',
  childcareDensity: 'Modern childcare/daycare inventories are used as a public proxy for the report C0 factor.',
  walkabilityPoiDensity: 'Supplemental POIs are reconstructed from public/open sources and have mixed confidence.',
  class3CrosswalkDensity: 'Class-3 crosswalk density is treated as pressure rather than a benefit metric.',
  pedestrianCrashDensity:
    'ICBC crash summaries are mapped reported-location concentrations, not exposure-adjusted risk.',
  communityWalkBalanced: 'Precomputed walkability variant; only populated on the Community polygons boundary.',
  communityWalkInfrastructure: 'Precomputed walkability variant; only populated on the Community polygons boundary.',
  communityWalkAccess: 'Precomputed walkability variant; only populated on the Community polygons boundary.',
  communityWalkSafetyAdjusted: 'Precomputed walkability variant; only populated on the Community polygons boundary.',
  communityWalkSupplementedLocal: 'Precomputed walkability variant; only populated on the Community polygons boundary.',
  walkabilityMiSurface:
    'Zonal mean of the 30m citywide MI raster; only meaningful for Prince George-area boundaries and computed only when weighted.',
  canopyProxyRatio: 'Derived from tree inventory buffers and forest/open-space proxies, not remote-sensing canopy.',
  shadeGap: 'Screening proxy for planning triage, not a validated heat exposure model.',
  cimdComposite: 'Area-level deprivation context; do not infer individual deprivation.',
  cimdResidentialInstability: 'Area-level deprivation context; do not infer individual deprivation.',
  cimdEconomicDependency: 'Area-level deprivation context; do not infer individual deprivation.',
  cimdSituationalVulnerability: 'Area-level deprivation context; do not infer individual deprivation.',
  cimdEthnoCulturalComposition: 'Area-level deprivation context; do not infer individual deprivation.',
  healthyFoodOutletAccess1km: 'Experimental classification from OSM/CityPG POIs; review outlet classes before use.',
  retailServiceAccess1km: 'OSM completeness varies by neighbourhood and CityPG licence categories are broad.',
  geocodedBusinessDensity:
    'BC Address Geocoder locations are address-level; some matches are block-level or shared-building locations.',
}

const METRIC_INDEX_MODULE: Record<ScoreMetricKey, ScoreIndexModule> = {
  overallDensity: 'localContext',
  lowCostDensity: 'localContext',
  referenceDensity: 'localContext',
  networkVariety: 'localContext',
  parameterVariety: 'localContext',
  activeShare: 'localContext',
  monitorCount: 'localContext',
  parkDensity: 'environmentalBurden',
  parkAreaRatio: 'environmentalBurden',
  trailDensity: 'environmentalBurden',
  amenityDensity: 'localContext',
  parkAccessGap1Mile: 'environmentalBurden',
  treeDensity: 'climateBurden',
  matureTreeDensity: 'climateBurden',
  forestAreaRatio: 'climateBurden',
  coolingFacilityDensity: 'climateBurden',
  responseFacilityDensity: 'localContext',
  restaurantDensity: 'localContext',
  foodRiskScore: 'environmentalBurden',
  criticalViolationRate: 'environmentalBurden',
  followUpRate: 'environmentalBurden',
  populationDensity: 'socialVulnerability',
  parcelDensity: 'localContext',
  avgAssessedValue: 'socialVulnerability',
  valueGrowth10y: 'environmentalBurden',
  buildingAge: 'environmentalBurden',
  pre1980HousingShare: 'environmentalBurden',
  vacantParcelShare: 'environmentalBurden',
  multiFamilyShare: 'socialVulnerability',
  commercialShare: 'localContext',
  landValueShare: 'environmentalBurden',
  crimeDensity: 'environmentalBurden',
  crimePerCapita: 'environmentalBurden',
  recentCrimeShare: 'environmentalBurden',
  transitStopDensity: 'environmentalBurden',
  accessibleTransitStopDensity: 'environmentalBurden',
  transitShelterDensity: 'environmentalBurden',
  frequentTransitStopAccess: 'environmentalBurden',
  transitServiceSpan: 'environmentalBurden',
  transitTripsPerStop: 'environmentalBurden',
  accessibleFrequentTransitAccess: 'environmentalBurden',
  sidewalkDensity: 'environmentalBurden',
  walkwayDensity: 'environmentalBurden',
  walkabilityIntersectionDensity: 'environmentalBurden',
  walkabilityCrossingDensity: 'environmentalBurden',
  childcareDensity: 'localContext',
  walkabilityPoiDensity: 'localContext',
  class3CrosswalkDensity: 'environmentalBurden',
  pedestrianCrashDensity: 'environmentalBurden',
  communityWalkBalanced: 'localContext',
  communityWalkInfrastructure: 'localContext',
  communityWalkAccess: 'localContext',
  communityWalkSafetyAdjusted: 'localContext',
  communityWalkSupplementedLocal: 'localContext',
  walkabilityMiSurface: 'localContext',
  parkWalk10Access: 'environmentalBurden',
  parkWalk20Access: 'environmentalBurden',
  coolingWalk15Access: 'climateBurden',
  parkTransit20Access: 'environmentalBurden',
  serviceAccessComposite: 'environmentalBurden',
  canopyProxyRatio: 'climateBurden',
  shadeGap: 'climateBurden',
  cimdComposite: 'socialVulnerability',
  cimdResidentialInstability: 'socialVulnerability',
  cimdEconomicDependency: 'socialVulnerability',
  cimdSituationalVulnerability: 'socialVulnerability',
  cimdEthnoCulturalComposition: 'socialVulnerability',
  healthyFoodOutletAccess1km: 'environmentalBurden',
  retailServiceAccess1km: 'environmentalBurden',
  educationFacilityAccess1km: 'localContext',
  geocodedBusinessDensity: 'localContext',
}

const METRIC_INDEX_DOMAIN: Record<ScoreMetricKey, ScoreIndexDomain> = {
  overallDensity: 'monitoring',
  lowCostDensity: 'monitoring',
  referenceDensity: 'monitoring',
  networkVariety: 'monitoring',
  parameterVariety: 'monitoring',
  activeShare: 'monitoring',
  monitorCount: 'monitoring',
  parkDensity: 'builtEnvironment',
  parkAreaRatio: 'builtEnvironment',
  trailDensity: 'builtEnvironment',
  amenityDensity: 'services',
  parkAccessGap1Mile: 'builtEnvironment',
  treeDensity: 'heat',
  matureTreeDensity: 'heat',
  forestAreaRatio: 'heat',
  coolingFacilityDensity: 'heat',
  responseFacilityDensity: 'services',
  restaurantDensity: 'services',
  foodRiskScore: 'foodSafety',
  criticalViolationRate: 'foodSafety',
  followUpRate: 'foodSafety',
  populationDensity: 'demographics',
  parcelDensity: 'housing',
  avgAssessedValue: 'socioeconomic',
  valueGrowth10y: 'housing',
  buildingAge: 'builtEnvironment',
  pre1980HousingShare: 'builtEnvironment',
  vacantParcelShare: 'housing',
  multiFamilyShare: 'housing',
  commercialShare: 'services',
  landValueShare: 'housing',
  crimeDensity: 'publicSafety',
  crimePerCapita: 'publicSafety',
  recentCrimeShare: 'publicSafety',
  transitStopDensity: 'transportationInfrastructure',
  accessibleTransitStopDensity: 'transportationInfrastructure',
  transitShelterDensity: 'transportationInfrastructure',
  frequentTransitStopAccess: 'transportationInfrastructure',
  transitServiceSpan: 'transportationInfrastructure',
  transitTripsPerStop: 'transportationInfrastructure',
  accessibleFrequentTransitAccess: 'transportationInfrastructure',
  sidewalkDensity: 'transportationInfrastructure',
  walkwayDensity: 'transportationInfrastructure',
  walkabilityIntersectionDensity: 'transportationInfrastructure',
  walkabilityCrossingDensity: 'transportationInfrastructure',
  childcareDensity: 'services',
  walkabilityPoiDensity: 'services',
  class3CrosswalkDensity: 'transportationInfrastructure',
  pedestrianCrashDensity: 'publicSafety',
  communityWalkBalanced: 'builtEnvironment',
  communityWalkInfrastructure: 'builtEnvironment',
  communityWalkAccess: 'builtEnvironment',
  communityWalkSafetyAdjusted: 'builtEnvironment',
  communityWalkSupplementedLocal: 'builtEnvironment',
  walkabilityMiSurface: 'builtEnvironment',
  parkWalk10Access: 'builtEnvironment',
  parkWalk20Access: 'builtEnvironment',
  coolingWalk15Access: 'heat',
  parkTransit20Access: 'transportationInfrastructure',
  serviceAccessComposite: 'services',
  canopyProxyRatio: 'heat',
  shadeGap: 'heat',
  cimdComposite: 'socioeconomic',
  cimdResidentialInstability: 'housing',
  cimdEconomicDependency: 'socioeconomic',
  cimdSituationalVulnerability: 'demographics',
  cimdEthnoCulturalComposition: 'demographics',
  healthyFoodOutletAccess1km: 'services',
  retailServiceAccess1km: 'services',
  educationFacilityAccess1km: 'services',
  geocodedBusinessDensity: 'services',
}

const METRIC_VALUE_BEHAVIOR: Partial<Record<ScoreMetricKey, ScoreMetricValueBehavior>> = {
  overallDensity: 'inverseContinuous',
  lowCostDensity: 'inverseContinuous',
  referenceDensity: 'inverseContinuous',
  networkVariety: 'inverseContinuous',
  parameterVariety: 'inverseContinuous',
  activeShare: 'inverseContinuous',
  parkDensity: 'inverseContinuous',
  parkAreaRatio: 'inverseContinuous',
  trailDensity: 'inverseContinuous',
  amenityDensity: 'inverseContinuous',
  parkAccessGap1Mile: 'continuous',
  treeDensity: 'inverseContinuous',
  matureTreeDensity: 'inverseContinuous',
  forestAreaRatio: 'inverseContinuous',
  coolingFacilityDensity: 'inverseContinuous',
  responseFacilityDensity: 'inverseContinuous',
  restaurantDensity: 'inverseContinuous',
  transitStopDensity: 'inverseContinuous',
  accessibleTransitStopDensity: 'inverseContinuous',
  transitShelterDensity: 'inverseContinuous',
  frequentTransitStopAccess: 'inverseContinuous',
  transitServiceSpan: 'inverseContinuous',
  transitTripsPerStop: 'inverseContinuous',
  accessibleFrequentTransitAccess: 'inverseContinuous',
  sidewalkDensity: 'inverseContinuous',
  walkwayDensity: 'inverseContinuous',
  walkabilityIntersectionDensity: 'inverseContinuous',
  walkabilityCrossingDensity: 'inverseContinuous',
  childcareDensity: 'inverseContinuous',
  walkabilityPoiDensity: 'inverseContinuous',
  parkWalk10Access: 'inverseContinuous',
  parkWalk20Access: 'inverseContinuous',
  coolingWalk15Access: 'inverseContinuous',
  parkTransit20Access: 'inverseContinuous',
  serviceAccessComposite: 'inverseContinuous',
  healthyFoodOutletAccess1km: 'inverseContinuous',
  retailServiceAccess1km: 'inverseContinuous',
  educationFacilityAccess1km: 'inverseContinuous',
  geocodedBusinessDensity: 'inverseContinuous',
  canopyProxyRatio: 'inverseContinuous',
  avgAssessedValue: 'inverseContinuous',
  multiFamilyShare: 'inverseContinuous',
}

const METRIC_MISSING_DATA_POLICY: Partial<Record<ScoreMetricKey, ScoreMissingDataPolicy>> = {
  cimdComposite: 'excludeRegion',
  cimdResidentialInstability: 'excludeRegion',
  cimdEconomicDependency: 'excludeRegion',
  cimdSituationalVulnerability: 'excludeRegion',
  cimdEthnoCulturalComposition: 'excludeRegion',
  shadeGap: 'neutral',
  canopyProxyRatio: 'neutral',
  coolingWalk15Access: 'neutral',
}

function metricDataSourceLabel(category: ScoreMetricDefinition['category']): string {
  if (category === 'airQuality') return 'Air quality monitor inventory'
  if (category === 'parksRec') return 'City of Prince George parks, trails, and amenities'
  if (category === 'heatShade') return 'City/open-data heat and shade proxy layers'
  if (category === 'foodSafety') return 'Northern Health food facility inspections'
  if (category === 'demographics') return 'Statistics Canada census boundary data'
  if (category === 'property') return 'BC Assessment parcel data'
  if (category === 'safety') return 'City of Prince George crime incidents'
  if (category === 'transit') return 'City of Prince George transit stop inventory'
  if (category === 'walkability') return 'Pedestrian Network Study public-data reconstruction'
  if (category === 'deprivation') return 'Statistics Canada CIMD 2021'
  if (category === 'healthyPlanPg') return 'HealthyPlan Prince George derived inputs'
  return 'PGMaps data source'
}

function metricSourceUrl(category: ScoreMetricDefinition['category']): string | undefined {
  if (category === 'transit') return 'https://www.bctransit.com/open-data/'
  if (category === 'walkability') return 'https://www.princegeorge.ca/city-hall/maps-information-requests/open-data'
  if (category === 'deprivation') return 'https://www150.statcan.gc.ca/n1/pub/45-20-0001/452000012023001-eng.htm'
  if (category === 'healthyPlanPg') return '/data/healthyplan-pg/manifest.json'
  if (category === 'heatShade' || category === 'parksRec')
    return 'https://www.princegeorge.ca/city-hall/maps-information-requests/open-data'
  return undefined
}

export const SCORE_METRICS: ScoreMetricDefinition[] = SCORE_METRIC_BASES.map((metric) => ({
  ...metric,
  direction: METRIC_DIRECTION[metric.key],
  component: METRIC_COMPONENT[metric.key],
  dataSourceLabel: metricDataSourceLabel(metric.category),
  spatialMethod: METRIC_SPATIAL_METHOD[metric.key],
  uncertainty: METRIC_UNCERTAINTY[metric.key],
  caveat: METRIC_CAVEATS[metric.key],
  directionLabel: METRIC_DIRECTION[metric.key] === 'higherIsWorse' ? 'lower helps' : 'higher helps',
  sourceUrl: metricSourceUrl(metric.category),
  freshnessLabel:
    metric.category === 'deprivation'
      ? '2021 Census / CIMD correction 2024'
      : metric.category === 'transit'
        ? 'Latest synced CityPG/BC Transit data'
        : metric.category === 'walkability'
          ? 'Latest bundled walkability reconstruction layers'
          : 'Latest bundled PGMaps data',
  comparisonBasis: 'Compared within the currently loaded boundary level',
  indexModule: METRIC_INDEX_MODULE[metric.key],
  indexDomain: METRIC_INDEX_DOMAIN[metric.key],
  valueBehavior:
    METRIC_VALUE_BEHAVIOR[metric.key] ??
    (METRIC_DIRECTION[metric.key] === 'higherIsWorse' ? 'continuous' : 'inverseContinuous'),
  missingDataPolicy: METRIC_MISSING_DATA_POLICY[metric.key] ?? 'neutral',
  proxyLevel:
    metric.category === 'deprivation' || metric.category === 'demographics' || metric.category === 'property'
      ? 'proxy'
      : 'experimental',
}))

const RECIPE_CREATED_METRIC_KEYS = new Set<ScoreMetricKey>([
  'healthyFoodOutletAccess1km',
  'retailServiceAccess1km',
  'educationFacilityAccess1km',
  'geocodedBusinessDensity',
])

export interface ScoreMetricRegistry {
  metrics: ScoreMetricDefinition[]
  builtInMetrics: ScoreMetricDefinition[]
  recipeMetrics: ScoreMetricDefinition[]
  byKey: ReadonlyMap<ScoreMetricKey, ScoreMetricDefinition>
  has: (key: ScoreMetricKey) => boolean
  get: (key: ScoreMetricKey) => ScoreMetricDefinition | undefined
}

export function createScoreMetricRegistry(
  metrics: ScoreMetricDefinition[],
  recipeMetricKeys: ReadonlySet<ScoreMetricKey> = RECIPE_CREATED_METRIC_KEYS,
): ScoreMetricRegistry {
  const byKey = new Map<ScoreMetricKey, ScoreMetricDefinition>()
  const builtInMetrics: ScoreMetricDefinition[] = []
  const recipeMetrics: ScoreMetricDefinition[] = []

  metrics.forEach((metric) => {
    byKey.set(metric.key, metric)
    if (recipeMetricKeys.has(metric.key)) recipeMetrics.push(metric)
    else builtInMetrics.push(metric)
  })

  return {
    metrics,
    builtInMetrics,
    recipeMetrics,
    byKey,
    has: (key) => byKey.has(key),
    get: (key) => byKey.get(key),
  }
}

export const SCORE_METRIC_REGISTRY = createScoreMetricRegistry(SCORE_METRICS)

export const SCORE_METRICS_BY_CATEGORY = SCORE_METRICS.reduce(
  (acc, metric) => {
    if (!acc[metric.category]) acc[metric.category] = []
    acc[metric.category].push(metric)
    return acc
  },
  {} as Record<string, ScoreMetricDefinition[]>,
)

export const DENSITY_METRIC_OPTIONS: ScoreMetricKey[] = [
  'overallDensity',
  'lowCostDensity',
  'referenceDensity',
  'monitorCount',
  'parkDensity',
  'trailDensity',
  'amenityDensity',
  'treeDensity',
  'matureTreeDensity',
  'coolingFacilityDensity',
  'responseFacilityDensity',
  'restaurantDensity',
  'populationDensity',
  'parcelDensity',
  'avgAssessedValue',
  'valueGrowth10y',
  'buildingAge',
  'crimeDensity',
  'crimePerCapita',
  'transitStopDensity',
  'accessibleTransitStopDensity',
  'transitShelterDensity',
  'frequentTransitStopAccess',
  'transitServiceSpan',
  'transitTripsPerStop',
  'accessibleFrequentTransitAccess',
  'sidewalkDensity',
  'walkwayDensity',
  'walkabilityIntersectionDensity',
  'walkabilityCrossingDensity',
  'childcareDensity',
  'walkabilityPoiDensity',
  'class3CrosswalkDensity',
  'pedestrianCrashDensity',
  'parkWalk10Access',
  'parkWalk20Access',
  'coolingWalk15Access',
  'parkTransit20Access',
  'serviceAccessComposite',
  'canopyProxyRatio',
  'shadeGap',
  'cimdComposite',
  'cimdResidentialInstability',
  'cimdEconomicDependency',
  'cimdSituationalVulnerability',
  'cimdEthnoCulturalComposition',
]
