import type { ScoreMetricKey, ScoreMetricWeightMap } from '../types'
import { BC_ENVIRO_SCREEN_METRIC_KEYS } from './bcEnviroScreenMetrics'

export const ZERO_WEIGHTS: ScoreMetricWeightMap = {
  overallDensity: 0,
  lowCostDensity: 0,
  referenceDensity: 0,
  networkVariety: 0,
  parameterVariety: 0,
  activeShare: 0,
  monitorCount: 0,
  parkDensity: 0,
  parkAreaRatio: 0,
  trailDensity: 0,
  amenityDensity: 0,
  parkAccessGap1Mile: 0,
  treeDensity: 0,
  matureTreeDensity: 0,
  forestAreaRatio: 0,
  coolingFacilityDensity: 0,
  responseFacilityDensity: 0,
  restaurantDensity: 0,
  foodRiskScore: 0,
  criticalViolationRate: 0,
  followUpRate: 0,
  populationDensity: 0,
  parcelDensity: 0,
  avgAssessedValue: 0,
  valueGrowth10y: 0,
  buildingAge: 0,
  pre1980HousingShare: 0,
  vacantParcelShare: 0,
  multiFamilyShare: 0,
  commercialShare: 0,
  landValueShare: 0,
  crimeDensity: 0,
  crimePerCapita: 0,
  recentCrimeShare: 0,
  transitStopDensity: 0,
  accessibleTransitStopDensity: 0,
  transitShelterDensity: 0,
  frequentTransitStopAccess: 0,
  transitServiceSpan: 0,
  transitTripsPerStop: 0,
  accessibleFrequentTransitAccess: 0,
  sidewalkDensity: 0,
  walkwayDensity: 0,
  walkabilityIntersectionDensity: 0,
  walkabilityCrossingDensity: 0,
  childcareDensity: 0,
  walkabilityPoiDensity: 0,
  class3CrosswalkDensity: 0,
  pedestrianCrashDensity: 0,
  communityWalkBalanced: 0,
  communityWalkInfrastructure: 0,
  communityWalkAccess: 0,
  communityWalkSafetyAdjusted: 0,
  communityWalkSupplementedLocal: 0,
  walkabilityMiSurface: 0,
  parkWalk10Access: 0,
  parkWalk20Access: 0,
  coolingWalk15Access: 0,
  parkTransit20Access: 0,
  serviceAccessComposite: 0,
  canopyProxyRatio: 0,
  shadeGap: 0,
  cimdComposite: 0,
  cimdResidentialInstability: 0,
  cimdEconomicDependency: 0,
  cimdSituationalVulnerability: 0,
  cimdEthnoCulturalComposition: 0,
  healthyFoodOutletAccess1km: 0,
  retailServiceAccess1km: 0,
  educationFacilityAccess1km: 0,
  geocodedBusinessDensity: 0,
  ...Object.fromEntries(BC_ENVIRO_SCREEN_METRIC_KEYS.map((key) => [key, 0])),
}

export const DEFAULT_SCORE_WEIGHTS: ScoreMetricWeightMap = {
  ...ZERO_WEIGHTS,
  overallDensity: 45,
  lowCostDensity: 15,
  referenceDensity: 25,
  networkVariety: 8,
  parameterVariety: 4,
  activeShare: 3,
}

export function createDefaultWeights(): ScoreMetricWeightMap {
  return { ...DEFAULT_SCORE_WEIGHTS }
}

export function createMetricValueMap(initial = 0): Record<ScoreMetricKey, number> {
  return {
    overallDensity: initial,
    lowCostDensity: initial,
    referenceDensity: initial,
    networkVariety: initial,
    parameterVariety: initial,
    activeShare: initial,
    monitorCount: initial,
    parkDensity: initial,
    parkAreaRatio: initial,
    trailDensity: initial,
    amenityDensity: initial,
    parkAccessGap1Mile: initial,
    treeDensity: initial,
    matureTreeDensity: initial,
    forestAreaRatio: initial,
    coolingFacilityDensity: initial,
    responseFacilityDensity: initial,
    restaurantDensity: initial,
    foodRiskScore: initial,
    criticalViolationRate: initial,
    followUpRate: initial,
    populationDensity: initial,
    parcelDensity: initial,
    avgAssessedValue: initial,
    valueGrowth10y: initial,
    buildingAge: initial,
    pre1980HousingShare: initial,
    vacantParcelShare: initial,
    multiFamilyShare: initial,
    commercialShare: initial,
    landValueShare: initial,
    crimeDensity: initial,
    crimePerCapita: initial,
    recentCrimeShare: initial,
    transitStopDensity: initial,
    accessibleTransitStopDensity: initial,
    transitShelterDensity: initial,
    frequentTransitStopAccess: initial,
    transitServiceSpan: initial,
    transitTripsPerStop: initial,
    accessibleFrequentTransitAccess: initial,
    sidewalkDensity: initial,
    walkwayDensity: initial,
    walkabilityIntersectionDensity: initial,
    walkabilityCrossingDensity: initial,
    childcareDensity: initial,
    walkabilityPoiDensity: initial,
    class3CrosswalkDensity: initial,
    pedestrianCrashDensity: initial,
    communityWalkBalanced: initial,
    communityWalkInfrastructure: initial,
    communityWalkAccess: initial,
    communityWalkSafetyAdjusted: initial,
    communityWalkSupplementedLocal: initial,
    walkabilityMiSurface: initial,
    parkWalk10Access: initial,
    parkWalk20Access: initial,
    coolingWalk15Access: initial,
    parkTransit20Access: initial,
    serviceAccessComposite: initial,
    canopyProxyRatio: initial,
    shadeGap: initial,
    cimdComposite: initial,
    cimdResidentialInstability: initial,
    cimdEconomicDependency: initial,
    cimdSituationalVulnerability: initial,
    cimdEthnoCulturalComposition: initial,
    healthyFoodOutletAccess1km: initial,
    retailServiceAccess1km: initial,
    educationFacilityAccess1km: initial,
    geocodedBusinessDensity: initial,
    ...Object.fromEntries(BC_ENVIRO_SCREEN_METRIC_KEYS.map((key) => [key, initial])),
  }
}
